---
# file: compute.yml

- hosts: compute
  become: yes
  vars_files:
    - private/vars/common.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: metrics, when: ansible_service_mgr == 'systemd', tags: metrics }
    - { role: ganglia, when: ansible_distribution == 'CentOS', tags: ganglia }
    - { role: storage, when: ansible_distribution == 'CentOS', tags: storage }
    - { role: compute, when: ansible_distribution == 'CentOS', tags: compute }

# vim: set sw=2 ts=2:
