---
# file: compute.yml

- hosts: compute
  become: yes
  remote_user: provisioning
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - private/vars/common.yml
    - "private/vars/{{ ansible_os_family }}.yml"
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: ganglia, when: ansible_distribution == 'CentOS', tags: ganglia }
    - { role: storage, when: ansible_distribution == 'CentOS', tags: storage }
    - { role: compute, when: ansible_distribution == 'CentOS', tags: compute }

# vim: set sw=2 ts=2:
