---
# file: compute.yml

- hosts: compute
  sudo: yes
  user: provisioning
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - private/vars/common.yml
    - "private/vars/{{ ansible_os_family }}.yml"
    - private/vars/ipsets.yml
  roles:
    - common
    - ganglia
    - sssd
    - glusterfs
    - compute
    - munin

# vim: set sw=2 ts=2:
