---
# file: dspace.yml

- hosts: dspace
  become: yes
  remote_user: provisioning
  vars_files:
    - private/vars/common.yml
    - private/vars/dspace.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - postgres
    - munin
    - { role: dspace, when: ansible_os_family == 'Debian', tags: dspace }

# vim: set sw=2 ts=2:
