---
# file: nomads.yml

- hosts: nomads:grafana
  become: yes
  remote_user: provisioning
  vars_files:
    - private/vars/common.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - munin

# vim: set sw=2 ts=2:
