---
# file: nomads.yml

- hosts: nomads:odk:grafana
  become: yes
  user: provisioning
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - private/vars/common.yml
    - "private/vars/{{ ansible_os_family }}.yml"
    - private/vars/ipsets.yml
  roles:
    - common

# vim: set sw=2 ts=2:
