---
# file: postgres.yml

- hosts: postgres
  become: yes
  vars_files:
    - private/vars/common.yml
    - private/vars/metrics.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - postgres
    - munin
    - { role: metrics, when: ansible_service_mgr == 'systemd', tags: metrics }

# vim: set sw=2 ts=2:
