---

- hosts: solr
  become: yes
  user: provisioning
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - private/vars/common.yml
    - "private/vars/{{ ansible_os_family }}.yml"
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: solr, when: ansible_distribution == 'Ubuntu', tags: solr }

# vim: set sw=2 ts=2:
