---

- hosts: solr
  become: yes
  vars_files:
    - private/vars/common.yml
    - private/vars/metrics.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: metrics, when: ansible_service_mgr == 'systemd', tags: metrics }
    - { role: solr, when: ansible_distribution == 'Ubuntu', tags: solr }

# vim: set sw=2 ts=2:
