---
# file: storage.yml

- hosts: storage
  become: yes
  user: provisioning
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - private/vars/common.yml
    - "private/vars/{{ ansible_os_family }}.yml"
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: ganglia, when: ansible_distribution == 'CentOS', tags: glusterfs }
    - { role: glusterfs, when: ansible_distribution == 'CentOS', tags: glusterfs }

# vim: set sw=2 ts=2:
