---
# file: storage.yml

- hosts: storage
  become: yes
  vars_files:
    - private/vars/common.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - sssd
    - munin
    - { role: ganglia, when: ansible_distribution == 'CentOS', tags: ganglia }
    - { role: storage, when: ansible_distribution == 'CentOS', tags: storage }

# vim: set sw=2 ts=2:
