---
# file: web.yml

- hosts: web
  become: yes
  vars_files:
    - private/vars/common.yml
    - private/vars/metrics.yml
    - private/vars/ipsets.yml
  roles:
    - common
    - munin
    - { role: metrics, when: ansible_service_mgr == 'systemd', tags: metrics }
    - web

# vim: set sw=2 ts=2:
