---
#file - roles/common/defaults/main.yml


# list of sysadmin(s) email addresses used by lsi & hp RAID monitoring scripts,
# cron-apt & backup scripts to alert on errors
sysadmin_emails:
  - mwangi@example.co.ke

# settings for root's .mailrc on hosts that
# use the RAID monitoring scripts
mailrc_smtp_server: smtp.example.co.ke
mailrc_from_email: mwangi@example.co.ke
mailrc_auth_user: mwangi@example.co.ke
mailrc_auth_pass: A2YtYma2i1D1

## use UTC as the default timezone
timezone: Etc/UTC

# See: https://github.com/restic/restic/releases
restic_version: 0.9.1
restic_url: https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2
restic_url_checksum: f7f76812fa26ca390029216d1378e5504f18ba5dde790878dfaa84afef29bda7
restic_binary_path: /usr/local/bin/restic

# vim: set ts=2 sw=2:
