---
#file - roles/common/defaults/main.yml

# list of email addresses for RAID admins used
# by lsi and hp RAID monitoring scripts to alert
# on errors
raid_admins:
  - mwangi@example.co.ke

# settings for root's .mailrc on hosts that
# use the RAID monitoring scripts
mailrc_smtp_server: smtp.example.co.ke
mailrc_from_email: mwangi@example.co.ke

# list of email addresses to send cron-apt
# error mails to
cron_apt_admins:
  - mwangi@example.co.ke

# vim: set ts=2 sw=2:
