---
#file - roles/common/defaults/main.yml


# list of sysadmin(s) email addresses used by lsi & hp RAID monitoring scripts,
# cron-apt & backup scripts to alert on errors
sysadmin_emails:
  - mwangi@example.co.ke

# settings for root's .mailrc on hosts that
# use the RAID monitoring scripts
mailrc_smtp_server: smtp.example.co.ke
mailrc_from_email: mwangi@example.co.ke
mailrc_auth_user: mwangi@example.co.ke
mailrc_auth_pass: A2YtYma2i1D1

# vim: set ts=2 sw=2:
