---
# file - roles/common/defaults/main.yml


# list of sysadmin(s) email addresses used by lsi & hp RAID monitoring scripts,
# cron-apt & backup scripts to alert on errors
sysadmin_emails:
  - mwangi@example.co.ke

# settings for root's .mailrc on hosts that
# use the RAID monitoring scripts
mailrc_smtp_server: smtp.example.co.ke
mailrc_from_email: mwangi@example.co.ke
mailrc_auth_user: mwangi@example.co.ke
mailrc_auth_pass: A2YtYma2i1D1

# use UTC as the default timezone
timezone: Etc/UTC

# See: https://github.com/restic/restic/releases
restic_version: 0.14.0
restic_url: https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2
# sha256sum
restic_url_checksum: c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165
restic_binary_path: /usr/local/bin/restic
# list of restic backup paths
restic_backup_paths:
  - /etc

fail2ban_maxretry: 6
# 1 hour in seconds
fail2ban_findtime: 3600
# 2 weeks in seconds
fail2ban_bantime: 1209600
fail2ban_ignoreip: 172.26.0.0/16 172.27.0.0/16 192.168.5.0/24 41.204.190.18/32 196.188.105.129/32

# vim: set ts=2 sw=2:
