---
# file: defaults/main.yml

# Forbid search bots via the "X-Robots-Tag" HTTP header?
# False on production, True on development!
nginx_forbid_robots: false

# default assumes letsencrypt on primary domain, override in hostvars if using
# self-signed certificates, etc.
nginx_tls_cert: /etc/letsencrypt/live/{{ nginx_server_name }}/fullchain.pem
nginx_tls_key: /etc/letsencrypt/live/{{ nginx_server_name }}/privkey.pem
# Note: this is also defined in the web role, but we define it here also becau-
# se we use it in some tasks before we run the web role.
nginx_ssl_port: 443

# Use 301 (permanent) or 302 (temporary) redirects?
# 301 on production, 302 on development!
nginx_redirect_type: 301

# where to install DSpace
dspace_root: /home/dspace-install

# document root
nginx_root: '{{ dspace_root }}/webapps/xmlui'

# default dspace webapps
dspace_webapps:
  - { name: 'server', app_path: '{{ dspace_root }}/webapps/server', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/server.xml', db_pool_name: 'jdbc/dspaceApi' }
  - { name: 'rest', app_path: '{{ dspace_root }}/webapps/rest', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/rest.xml', db_pool_name: 'jdbc/dspaceApi' }

# default postgresql dspace db credentials
dspace_db_name: dspace
dspace_db_user: dspace
dspace_db_password: Mz97%tU64J

dspace_statistics_db_name: dspacestatistics
dspace_statistics_db_user: dspacestatistics
dspace_statistics_db_password: dspacestatistics
dspace_statistics_db_host: localhost
dspace_statistics_api_git_repo: https://github.com/ilri/dspace-statistics-api.git
dspace_statistics_api_git_version: v1.4.5
dspace_statistics_api_dir: /opt/ilri/dspace-statistics-api

# Port 8983 on DSpace 7
dspace_solr_server: http://localhost:8983/solr

dspace_explorer_server: prod.ares.codeobia.com

dspace_mail_server: smtp.office365.com
dspace_ldap_server: ldaps://AZCGNEROOT3.cgiarad.org:636/
# development hosts should override this to true in host_vars
dspace_mail_disabled: false

# CMYK/RGB iccprofiles for DSpace 5.6+ PDF thumbnails
dspace_ghostscript_prefix: /usr/share/color/icc/ghostscript

# command to use for pyvenv (Ubuntu 24.04 is Python 3.12)
pyvenv_command: python3.12 -m venv

# version 17 for DSpace 7
java_version_major: 17

# version 20 for DSpace 7
nodejs_version_major: 20

tomcat_user: dspace
tomcat_group: dspace
tomcat_user_home: /home/dspace
# See: https://tomcat.apache.org/download-90.cgi
tomcat_version: 9.0.102
tomcat_version_major: 9
tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
# sha512
tomcat_url_checksum: cbe407f17c813d9f83cab459e603df171f2e5782c3a0cdb4cfa00b0391a89cedf865c6d8972fc7e12210c69a8467ede5939f35bb0f3b41fa173b9ee83199768a
tomcat_path_prefix: /usr/local
tomcat_path: '{{ tomcat_path_prefix }}/apache-tomcat-{{ tomcat_version }}'

# install certbot + dependencies?
# True unless you're in development and using "localhost" + snakeoil certs
use_letsencrypt: true

# Dummy key
sherpa_romeo_apikey: 5DHH3N12-1362-11RG-923C-471E3TE2897G

# Dummy keys (override in host_vars)
google_analytics_key: G-XXXXXXXXXX
google_analytics_api_secret: XXXXXX-XXXXxxXxXxXXxxX

# vim: set sw=2 ts=2:
