---
# file: defaults/main.yml

# Forbid search bots via the "X-Robots-Tag" HTTP header?
# False on production, True on development!
nginx_forbid_robots: False

# 1 hour timeout
nginx_ssl_session_timeout: 1h
# 10MB -> 40,000 sessions
nginx_ssl_session_cache: shared:SSL:10m
# 1400 bytes to fit in one MTU (default is 16k!)
nginx_ssl_buffer_size: 1400
nginx_ssl_dhparam: /etc/ssl/certs/dhparam.pem
nginx_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
nginx_ssl_port: 443

# DNS resolvers for OCSP stapling (default to Cloudflare public DNS)
# See: https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling
nginx_ssl_stapling_resolver: '1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001]'

# default assumes letsencrypt on primary domain, override in hostvars if using
# self-signed certificates, etc.
nginx_tls_cert: /etc/letsencrypt/live/{{ nginx_server_name }}/fullchain.pem
nginx_tls_key: /etc/letsencrypt/live/{{ nginx_server_name }}/privkey.pem

# Use 301 (permanent) or 302 (temporary) redirects?
# 301 on production, 302 on development!
nginx_redirect_type: 301

# Enable HTTP Strict Transport Security?
# True on production, False on development!
nginx_enable_hsts: True

# where to install DSpace
dspace_root: /home/dspace

# document root
nginx_root: '{{ dspace_root }}/webapps/xmlui'

# default dspace webapps
dspace_webapps:
  - { name: 'ROOT', app_path: '{{ dspace_root }}/webapps/xmlui', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/ROOT.xml', db_pool_name: 'jdbc/dspaceWeb' }
  - { name: 'jspui', app_path: '{{ dspace_root }}/webapps/jspui', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/jspui.xml', db_pool_name: 'jdbc/dspaceWeb' }
  - { name: 'oai', app_path: '{{ dspace_root }}/webapps/oai', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/oai.xml', db_pool_name: 'jdbc/dspaceApi' }
  - { name: 'solr', app_path: '{{ dspace_root }}/webapps/solr', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/solr.xml' }
  - { name: 'rest', app_path: '{{ dspace_root }}/webapps/rest', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/rest.xml', db_pool_name: 'jdbc/dspaceApi' }

# default postgresql dspace db credentials
dspace_db_name: dspace
dspace_db_user: dspace
dspace_db_password: Mz97%tU64J

dspace_statistics_db_name: dspacestatistics
dspace_statistics_db_user: dspacestatistics
dspace_statistics_db_password: dspacestatistics
dspace_statistics_db_host: localhost
dspace_statistics_api_git_repo: https://github.com/alanorth/dspace-statistics-api.git
dspace_statistics_api_git_version: v0.5.2
dspace_statistics_api_dir: /opt/ilri/dspace-statistics-api

dspace_explorer_server: prod.ares.codeobia.com

# default mail server (development hosts should override this to blank in host_vars)
dspace_mail_server: smtp.serv.cgnet.com
dspace_ldap_server: ldaps://azcgneroot2.cgiarad.org:636/

# CMYK/RGB iccprofiles for DSpace 5.6+ PDF thumbnails
dspace_ghostscript_prefix: /usr/share/ghostscript/current

# command to use for pyvenv (Ubuntu 16.04 is Python 3.5)
pyvenv_command: pyvenv-3.5

# distribution can be oracle or openjdk
java_distribution: oracle
# version must be 8 (for now)
java_version_major: 8

tomcat_user: tomcat7
tomcat_group: tomcat7
tomcat_user_home: /usr/share/tomcat7
tomcat_version_major: 7

# install certbot + dependencies?
# True unless you're in development and using "localhost" + snakeoil certs
use_letsencrypt: True

# Directory root for Let's Encrypt certs
letsencrypt_root: /etc/letsencrypt/live

# Location of Let's Encrypt's certbot script
letsencrypt_certbot_path: /opt/certbot-auto

# vim: set sw=2 ts=2:
