---
# file: defaults/main.yml

# Forbid search bots via the "X-Robots-Tag" HTTP header?
# False on production, True on development!
nginx_forbid_robots: False

# 1 hour timeout
nginx_ssl_session_timeout: 1h
# 10MB -> 40,000 sessions
nginx_ssl_session_cache: shared:SSL:10m
# 1400 bytes to fit in one MTU (default is 16k!)
nginx_ssl_buffer_size: 1400
nginx_ssl_dhparam: /etc/ssl/certs/dhparam.pem
nginx_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
nginx_spdy_headers_comp: 6

# Use 301 (permanent) or 302 (temporary) redirects?
# 301 on production, 302 on development!
nginx_redirect_type: 301

# Enable HTTP Strict Transport Security?
# True on production, False on development!
nginx_enable_hsts: True

# where to install DSpace
dspace_root: /home/dspace

# document root
nginx_root: '{{ dspace_root }}/webapps/xmlui'

# default dspace webapps
dspace_webapps:
  - { name: 'ROOT', app_path: '{{ dspace_root }}/webapps/xmlui', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/ROOT.xml' }
  - { name: 'jspui', app_path: '{{ dspace_root }}/webapps/jspui', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/jspui.xml' }
  - { name: 'oai', app_path: '{{ dspace_root }}/webapps/oai', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/oai.xml' }
  - { name: 'solr', app_path: '{{ dspace_root }}/webapps/solr', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/solr.xml' }
  - { name: 'rest', app_path: '{{ dspace_root }}/webapps/rest', context_path: '/etc/tomcat{{ tomcat_version_major }}/Catalina/localhost/rest.xml' }

# default postgresql dspace db credentials
dspace_db_name: dspace
dspace_db_user: dspace
dspace_db_password: Mz97%tU64J

# default Oracle JDK version
java_version_major: 8

tomcat_user: tomcat7
tomcat_group: tomcat7
tomcat_user_home: /usr/share/tomcat7
tomcat_version_major: 7

# install certbot + dependencies?
# True unless you're in development and using "localhost" + snakeoil certs
use_letsencrypt: True

# Directory root for Let's Encrypt certs
letsencrypt_root: /etc/letsencrypt/live

# Location of Let's Encrypt's certbot script
letsencrypt_certbot_path: /opt/certbot-auto

# vim: set sw=2 ts=2:
