---
# file: defaults/main.yml

# Forbid search bots via the "X-Robots-Tag" HTTP header?
# False on production, True on development!
nginx_forbid_robots: false

# default assumes letsencrypt on primary domain, override in hostvars if using
# self-signed certificates, etc.
nginx_tls_cert: /etc/letsencrypt/live/{{ nginx_server_name }}/fullchain.pem
nginx_tls_key: /etc/letsencrypt/live/{{ nginx_server_name }}/privkey.pem
# Note: this is also defined in the web role, but we define it here also becau-
# se we use it in some tasks before we run the web role.
nginx_ssl_port: 443

# Use 301 (permanent) or 302 (temporary) redirects?
# 301 on production, 302 on development!
nginx_redirect_type: 301

# where to install DSpace
dspace_root: /home/dspace-install

# document root
nginx_root: '{{ dspace_root }}/webapps/xmlui'

# default dspace webapps
dspace_webapps:
  - { name: 'ROOT', app_path: '{{ dspace_root }}/webapps/xmlui', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/ROOT.xml', db_pool_name: 'jdbc/dspaceWeb' }
  - { name: 'oai', app_path: '{{ dspace_root }}/webapps/oai', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/oai.xml', db_pool_name: 'jdbc/dspaceApi' }
  - { name: 'solr', app_path: '{{ dspace_root }}/webapps/solr', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/solr.xml' }
  - { name: 'rest', app_path: '{{ dspace_root }}/webapps/rest', context_path: '{{ tomcat_path }}/conf/Catalina/localhost/rest.xml', db_pool_name: 'jdbc/dspaceApi' }

# default postgresql dspace db credentials
dspace_db_name: dspace
dspace_db_user: dspace
dspace_db_password: Mz97%tU64J

dspace_statistics_db_name: dspacestatistics
dspace_statistics_db_user: dspacestatistics
dspace_statistics_db_password: dspacestatistics
dspace_statistics_db_host: localhost
dspace_statistics_api_git_repo: https://github.com/ilri/dspace-statistics-api.git
dspace_statistics_api_git_version: v1.4.3
dspace_statistics_api_dir: /opt/ilri/dspace-statistics-api

dspace_explorer_server: prod.ares.codeobia.com

dspace_mail_server: smtp.office365.com
dspace_ldap_server: ldaps://AZCGNEROOT3.cgiarad.org:636/
# development hosts should override this to true in host_vars
dspace_mail_disabled: false

# CMYK/RGB iccprofiles for DSpace 5.6+ PDF thumbnails
dspace_ghostscript_prefix: /usr/share/color/icc/ghostscript
# needs to be a string or else Ansible translates it as a Python boolean, ie False
dspace_dev_mode: 'false'

# command to use for pyvenv (Ubuntu 22.04 is Python 3.10)
pyvenv_command: python3.10 -m venv

# version 8 for DSpace 6, version 17 for DSpace 7
java_version_major: 8

# version 14 for DSpace 6, version 18 for DSpace 7
nodejs_version_major: 14

tomcat_user: dspace
tomcat_group: dspace
tomcat_user_home: /home/dspace
# See: https://tomcat.apache.org/download-70.cgi
tomcat_version: 7.0.109
tomcat_version_major: 7
tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
# sha512
tomcat_url_checksum: 612e830913bf1401bc9540e2273e465b0ee7ef63750a9969a80f1e9da9edb4888aa621fcc6fa5ba23cff94a40e91eb97e3f969b8064dabd49b2d0ea29e59b57e
tomcat_path_prefix: /usr/local
tomcat_path: '{{ tomcat_path_prefix }}/apache-tomcat-{{ tomcat_version }}'

# install certbot + dependencies?
# True unless you're in development and using "localhost" + snakeoil certs
use_letsencrypt: true

# vim: set sw=2 ts=2:
