---
# file: roles/ganglia/handlers/main.yml

- name: restart gmond
  ansible.builtin.systemd:
    name: gmond
    state: restarted

- name: restart gmetad
  ansible.builtin.systemd:
    name: gmetad
    state: restarted

# vim: set sw=2 ts=2:
