---
# file: roles/web/handlers/main.yml

# When the nginx binary changes
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

# When configs or TLS certificates change
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
