---
# file: roles/web/handlers/main.yml

# For module changes
- name: restart apache2
  ansible.builtin.systemd_service:
    name: apache2
    state: restarted

# For config changes
- name: reload apache2
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded

# When the nginx binary changes
- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

# When configs or TLS certificates change
- name: reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: reload caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: reloaded

# vim: set sw=2 ts=2:
