---
# After running this role you should be able to query HPC's LDAP, ie:
#
# ldapsearch -x
# ...
# result: 0 Success
#
# # numResponses: 448
# # numEntries: 447

- name: Copy ldap.conf
  ansible.builtin.template:
    src: ldap.conf.j2
    dest: "{{ ldap_conf_dir }}/ldap.conf"
    owner: root
    group: root
    mode: "0644"

- name: Remove old CA certificates
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ local_ca_certs_dir }}/hpc-ca.asc"
    - "{{ ldap_conf_dir }}/cacerts/hpc-ca.asc"
    - "{{ ldap_conf_dir }}/cacerts/252fd4a1.0"
    - "{{ local_ca_certs_dir }}/hpc-ca.crt"
    - "{{ local_ca_certs_dir }}/hpc-ca-2017.crt"
    - /etc/pki/ca-trust/source/anchors/hpc-ca-2017.crt
    - "{{ local_ca_certs_dir }}/hpc-ca-2017.pem"

- name: Copy HPC CA certificate to trust store
  ansible.builtin.copy:
    src: hpc-ca-2022.asc
    dest: "{{ local_ca_certs_dir }}/hpc-ca-2022.asc"
    owner: root
    group: root
    mode: "0644"
  register: update_cert_bundle

- name: update trusted ca-certificates bundle
  when:
    - ansible_distribution == 'Ubuntu'
    - update_cert_bundle is changed
  ansible.builtin.command: /usr/sbin/update-ca-certificates --fresh

- name: update trusted ca-certificates bundle
  when:
    - ansible_distribution == 'CentOS'
    - update_cert_bundle is changed
  ansible.builtin.command: /usr/bin/update-ca-trust extract

- name: Install OpenLDAP utils
  ansible.builtin.package:
    name: openldap-clients
    state: present
  when: ansible_distribution == 'CentOS'
  tags: packages

# vim: set ts=2 sw=2:
