---
- name: Copy ldap.conf
  template: src=ldap.conf.j2 dest={{ ldap_conf_dir}}/ldap.conf owner=root group=root mode=0644

- name: Remove old CA certificates
  file: path={{ item }} state=absent
  with_items:
    - "{{ local_ca_certs_dir }}/hpc-ca.asc"
    - "{{ ldap_conf_dir }}/cacerts/hpc-ca.asc"
    - "{{ ldap_conf_dir }}/cacerts/252fd4a1.0"
    - "{{ local_ca_certs_dir }}/hpc-ca.crt"

- name: Copy HPC CA certificate to trust store
  copy: src=hpc-ca-2017.asc dest={{ local_ca_certs_dir }}/hpc-ca-2017.crt owner=root group=root mode=0644
  register: update_cert_bundle

- name: update trusted ca-certificates bundle
  when: ansible_distribution == 'Ubuntu' and update_cert_bundle|changed
  command: /usr/sbin/update-ca-certificates --fresh

- name: update trusted ca-certificates bundle
  when: ansible_distribution == 'CentOS' and update_cert_bundle|changed
  shell: /usr/bin/update-ca-trust enable && /usr/bin/update-ca-trust extract

- name: Install OpenLDAP utils
  yum: name=openldap-clients state=latest
  when: ansible_distribution == 'CentOS'
  tags: packages

# vim: set ts=2 sw=2:
