---
- name: Configure LDAP client
  ansible.builtin.import_tasks: ldap.yml
  tags: ldap

- name: Configure SSSD
  ansible.builtin.import_tasks: sssd.yml
  tags: sssd

- name: Configure sudoers
  ansible.builtin.import_tasks: sudoersd.yml
  tags: sudoers

# vim: set ts=2 sw=2:
