---
- name: Install sssd package
  ansible.builtin.package:
    name: [sssd, sssd-tools, sssd-ldap, oddjob-mkhomedir]
    state: present
  when: ansible_distribution == 'CentOS'
  tags: packages

- name: Install sssd package
  ansible.builtin.package:
    name: [sssd, sssd-tools]
    state: present
    cache_valid_time: 3600
  when: ansible_distribution == 'Ubuntu'
  tags: packages

# authconfig updates ldap.conf & adds TLS_CACERTDIR which overrides TLS_CACERT
# so we'll need to remove it from ldap.conf
- name: remove TLS_CACERTDIR in ldap.conf
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_release == 'Stream'
  ansible.builtin.lineinfile:
    path: "{{ ldap_conf_dir }}/ldap.conf"
    regexp: ^TLS_CACERTDIR
    state: absent

# TODO: this fails the first time sometimes. Perhaps I can check the current
# profile first and then run this with --force if needed?
- name: Configure sssd on CentOS Stream 8
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_release == 'Stream'
  ansible.builtin.command: authselect select sssd with-mkhomedir

- name: Configure sssd
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: "0600"
  notify: restart sssd

- name: Enable pam_mkhomedir
  ansible.builtin.copy:
    src: pam_mkhomedir
    dest: /usr/share/pam-configs/pam_mkhomedir
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == 'Ubuntu'

- name: Regenerate pam config
  ansible.builtin.command: pam-auth-update --package
  when: ansible_distribution == 'Ubuntu'

# Allow LDAP users with UIDs less than 1000 to log in.
# See: https://bugzilla.redhat.com/show_bug.cgi?id=1773567
- name: Change minimum PAM UID for SSH logins
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_release == 'Stream'
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: ^UID_MIN, line: UID_MIN 600 }
    - { regexp: ^SYS_UID_MAX, line: SYS_UID_MAX 599 }
    - { regexp: ^GID_MIN, line: GID_MIN 600 }
    - { regexp: ^SYS_GID_MAX, line: SYS_GID_MAX 599 }

- name: Add HPC to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars["hpc"].ansible_host }}.*hpc.*hpc\.ilri\.cgiar\.org$'
    line: "{{ hostvars['hpc'].ansible_host }} hpc hpc.ilri.cgiar.org"
    state: present

- name: Start and enable sssd service
  ansible.builtin.service:
    name: sssd
    state: started
    enabled: true

- name: Start and enable oddjobd service
  ansible.builtin.systemd:
    name: oddjobd
    state: started
    enabled: true
  when: ansible_distribution == 'CentOS'

# vim: set ts=2 sw=2:
