---
- name: Install ganglia-gmetad package
  yum: name=ganglia-gmetad state=present
  tags: packages

- name: Create gmetad configuration file
  copy: src=gmetad.conf dest=/etc/ganglia/gmetad.conf
  notify:
  - restart gmetad

- name: Start gmetad service
  systemd: name=gmetad state=started enabled=true

# vim: set sw=2 ts=2:
