---
- name: Install ganglia-gmond
  yum: name={{ item }} state=present
  with_items:
   - ganglia-gmond
  tags: packages

- name: Create gmond.conf
  template: src=gmond.conf.j2 dest=/etc/ganglia/gmond.conf
  notify: 
  - restart gmond

- name: Start gmond
  service: name=gmond state=started enabled=true

# vim: set sw=2 ts=2:
