---
- name: Install ganglia-gmond
  ansible.builtin.package:
    name: ganglia-gmond
    state: present
  tags: packages

- name: Create gmond.conf
  ansible.builtin.template:
    src: gmond.conf.j2
    dest: /etc/ganglia/gmond.conf
    owner: ganglia
    group: ganglia
    mode: "0640"
  notify:
    - restart gmond

# vim: set sw=2 ts=2:
