---
# file: roles/common/handlers/main.yml

# Remember, Ansible handlers are run in the order they are defined globally, not
# the order they are listed in the task's notify.
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

- name: restart ip6tables
  ansible.builtin.service:
    name: ip6tables
    state: restarted

- name: reload sshd
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: reloaded

# if NX(No eXecute (AMD)) or XD(eXecute Disable (Intel)) is already
# enabled in the BIOS, then you can't enable ExecShield using sysctl's
# kernel.exec-shield
# check if NX/XD is enabled in the BIOS
# $ dmesg | grep '[NX|DX]*protection'
- name: reload sysctl
  ignore_errors: true
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.conf

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted

# 2021-09-28: note to self, this should be defined after the firewalld and
# nftables handlers, as handlers are run in the order they are defined, not
# the order they are listed in the task's notify.
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

# ignore_errors: at times fails on some compute nodes
- name: start tuned
  ignore_errors: true
  ansible.builtin.service:
    name: tuned
    state: started

# ignore_errors: at times fails on some compute nodes
- name: start cpuspeed
  ignore_errors: true
  ansible.builtin.service:
    name: cpuspeed
    state: started

# vim: set sw=2 ts=2:
