---
# file: roles/common/handlers/main.yml

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart iptables-persistent
  service: name=iptables-persistent state=restarted

- name: reload sshd
  service: name={{ sshd_service_name }} state=reloaded

# if NX(No eXecute (AMD)) or XD(eXecute Disable (Intel)) is already
# enabled in the BIOS, then you can't enable ExecShield using sysctl's
# kernel.exec-shield
# check if NX/XD is enabled in the BIOS
# $ dmesg | grep '[NX|DX]*protection'
- name: reload sysctl
  ignore_errors: yes
  command: sysctl -p /etc/sysctl.conf

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart fail2ban
  systemd: name=fail2ban state=restarted

- name: reload systemd
  systemd: daemon_reload=yes

- name: restart nftables
  systemd: name=nftables state=restarted

# ignore_errors: at times fails on some compute nodes
- name: start tuned
  ignore_errors: yes
  service: name=tuned state=started

# ignore_errors: at times fails on some compute nodes
- name: start cpuspeed
  ignore_errors: yes
  service: name=cpuspeed state=started

# vim: set sw=2 ts=2:
