---
# file: roles/common/handlers/main.yml

# Remember, Ansible handlers are run in the order they are defined globally, not
# the order they are listed in the task's notify.
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

- name: restart ip6tables
  ansible.builtin.service:
    name: ip6tables
    state: restarted

- name: reload sshd
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: reloaded

- name: reload sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted

- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted

# 2021-09-28: note to self, this should be defined after the firewalld and
# nftables handlers, as handlers are run in the order they are defined, not
# the order they are listed in the task's notify.
# 2022-06-08: do not run fail2ban handlers on CentOS because we currently
# do not use fail2ban there (due to its hard dependency on firewalld).
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  when: ansible_distribution != 'CentOS'

- name: start tuned
  ansible.builtin.service:
    name: tuned
    state: started

- name: start cpuspeed
  ansible.builtin.service:
    name: cpuspeed
    state: started

# vim: set sw=2 ts=2:
