---
# file: tasks/main.yml

- include: postgresql-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and preferred_dbms == 'postgresql'
  tags: postgres

- include: mariadb-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and preferred_dbms == 'mariadb'
  tags: mariadb

- include: mysql-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and preferred_dbms == 'mysql'
  tags: mysql

# vim: set ts=2 sw=2:
