---
# Common setup for Nairobi and Addis HPC head nodes.

- name: Install SELinux utilities
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
      - python3-libsemanage.x86_64 # required by Ansible's seboolean module
    state: present
  tags: packages

# I'm not sure if we also need httpd_unified? In the past we did...
- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db

# HPC runs a web server for the wiki, mirrors, and a few other PHP applications
- name: Install web packages
  ansible.builtin.dnf:
    name:
      - httpd.x86_64
    state: present
  tags: packages

- name: Create user.slice override directory
  ansible.builtin.file:
    path: /etc/systemd/system/user.slice.d
    group: root
    owner: root
    mode: "0755"
    state: directory
  tags: limits

- name: Copy systemd user.slice override
  ansible.builtin.copy:
    src: etc/systemd/system/user.slice.d/override.conf
    dest: /etc/systemd/system/user.slice.d/override.conf
    owner: root
    group: root
    mode: "0644"
  tags: limits

- name: Configure Nairobi HPC head node
  ansible.builtin.import_tasks: hpc_nairobi.yml
  when:
    - slurm_head_node is defined
    - inventory_hostname == slurm_head_node
    - "'nairobi_compute' in group_names"
    - ansible_distribution_major_version is version('8', '==')

# vim: set sw=2 ts=2:
