---
# Try to codify the organic growth of HPC as a system into something we can ac-
# tually manage.

# Need to set SELinux to permissive for Apache httpd only:
#
#   semanage permissive -a httpd_t
#
# There is no Ansible module for semanage and we need this for DokuWiki.

# I'm not sure if we also need httpd_unified? In the past we did...
- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - httpd_use_fusefs
    - samba_enable_home_dirs
    - samba_share_fusefs
    - samba_export_all_ro
    - samba_export_all_rw
    - httpd_can_network_relay # for RStudio

# HPC runs a web server for the wiki, mirrors, and a few other PHP applications
- name: Install web packages
  ansible.builtin.dnf:
    name:
      - php-fpm.x86_64
      - php-gd.x86_64
      - php-intl.x86_64
      - php-json.x86_64
      - php-mbstring.x86_64
      - php-mysqlnd.x86_64
      - php-opcache.x86_64
      - php-pdo.x86_64
      - php-xml.x86_64
    state: present
  tags: packages

# HPC runs samba to do Windows filesharing for SegoliP
- name: Install samba packages
  ansible.builtin.dnf:
    name: samba.x86_64
    state: present
  tags: packages

- name: Install 389-ds-base
  ansible.builtin.dnf:
    name: 389-ds-base.x86_64
    state: present
  tags: packages

- name: Add systemd-tmpfiles config for dirsrv backups
  ansible.builtin.file:
    src: etc/tmpfiles.d/dirsrv-backups.conf
    dest: /etc/tmpfiles.d/dirsrv-backups.conf
    owner: root
    group: root
    mode: "0644"

# vim: set sw=2 ts=2:
