---
- name: Configure HPC head node
  ansible.builtin.import_tasks: hpc.yml
  when:
    - inventory_hostname == slurm_head_node
    - ansible_distribution_major_version is version('8', '==')

- name: Configure SLURM
  ansible.builtin.import_tasks: slurm.yml
  tags: slurm

# 2022-04-21: currently missing from CentOS 8:
#   - compat-libstdc++-33.x86_64
#   - argtable.x86_64 # for clustalo
#   - proj-epsg.x86_64 # for some R libraries
- name: Install extra packages (CentOS Stream 8)
  ansible.builtin.package:
    name:
      - apptainer.x86_64 # from EPEL, for viralrecon pipeline
      - bcl2fastq2 # from Illumina, in ILRI repo
      - boost-devel.x86_64 # for augustus
      - boost-iostreams.x86_64 # for augustus
      - cairo-devel.x86_64 # for genometools and others
      - cmake
      - compat-openssl10.x86_64 # for stuff compiled on CentOS 7
      - dbus-devel # required for SLURM 22.05.0 cgroup/v2
      - emacs.x86_64
      - environment-modules.x86_64
      - fftw-devel.x86_64 # for gromacs
      - firefox.x86_64
      - gcc-c++.x86_64 # for some R libraries
      - gdal-devel.x86_64 # for some R libraries
      - gdal.x86_64 # for libgdal.so.1
      - geos-devel.x86_64 # for some R libraries
      - glib2.x86_64 # for wise / Cegma
      - glpk-devel.x86_64 # for shannon_cpp
      - gnuplot.x86_64
      - graphviz
      - graphviz-devel.x86_64 # for some Python libraries
      - gsl-devel.x86_64 # needed for some R packages like HiCeekR
      - gsl.x86_64 # for fastSTRUCTURE
      - hdf5-devel.x86_64 # for some R libraries
      - htop.x86_64
      - java-11-openjdk.x86_64 # for lots of stuff
      - joe.x86_64 # some users need this
      - lapack.x86_64 # for presto
      - libXt-devel.x86_64 # for R/4.2.0 (X11/Intrinsic.h)
      - libXtst.x86_64 # for some X apps like CLC Genomics
      - libcurl-devel.x86_64 # for some R libraries
      - libgfortran.x86_64 # for R
      - libgfortran4-8.3.1-2.1.1.el7.x86_64 # for R compiled on CentOS 7 (in ILRI repo)
      - libgomp.x86_64 # for R
      - libicu.x86_64 # for R
      - libjpeg-turbo-devel.x86_64 # needed for some R packages like HiCeekR
      - libnsl.x86_64 # needed by binaries linked against older libc
      - libpng12.x86_64 # for pre-compiled blat binary
      - libstdc++.i686 # for 32-bit binaries
      - libtiff-devel.x86_64 # for some R libraries
      - libtool-ltdl.x86_64 # for pandaseq/2.7
      - libwebp-devel.x86_64 # for some R libraries
      - libxml2-devel.x86_64 # for some R libraries
      - libzstd-devel.x86_64 # for some R libraries
      - make.x86_64
      - mesa-libGLU-devel.x86_64 # for some R libraries
      - metis-devel.x86_64 # for shannon_cpp
      - nano.x86_64
      - ncurses-compat-libs.x86_64 # for some stuff compiled in CentOS 7
      - netcdf-devel # for some R packages
      - openblas.x86_64 # for scipy
      - openmpi.x86_64 # optional for abyss
      - openssl-devel.x86_64 # for R
      - pandoc.x86_64
      - pango-devel.x86_64 # for genometools and others
      - pcre2-devel.x86_64 # needed as of R/4.0
      - perl-Clone.x86_64 # for circos, see: https://hpc.ilri.cgiar.org/circos-software
      - perl-Config-General.noarch # for circos
      - perl-DBD-MySQL.x86_64 # for vep
      - perl-DBI.x86_64 # for vep, see: https://hpc.ilri.cgiar.org/vep-software
      - perl-Env.noarch # for masurca
      - perl-Font-TTF.noarch # for circos
      - perl-GD.x86_64 # for circos
      - perl-JSON.noarch # for vep
      - perl-LWP-Protocol-https.noarch # so perl can use https
      - perl-List-MoreUtils.noarch # for abricate
      - perl-Math-Round.noarch # for circos
      - perl-PerlIO-gzip.x86_64 # for vep
      - perl-Readonly.noarch # for circos
      - perl-Regexp-Common.noarch # for circos
      - perl-Statistics-Basic.noarch # for circos
      - perl-Text-Format.noarch # for circos
      - perl-Text-Soundex.x86_64 # for RepeatMasker
      - perl-parent.noarch # for some BioPerl scripts
      - perl-Params-Validate.x86_64 # for circos
      - perl-XML-LibXML # for sratoolkit fastq-dump
      - pigz.x86_64 # for SeqKit
      - proj-devel.x86_64 # for some R libraries
      - proj.x86_64 # for libproj.so.0
      - python3-numpy.x86_64 # for Trinity as of v2.6.6
      - python3-setuptools.noarch # needed by some Python scripts to load entrypoint
      - python36.x86_64
      - readline-devel.x86_64 # for R/4.2.0
      - rsync.x86_64
      - screen.x86_64
      - sparsehash-devel.x86_64 # for shannon_cpp
      - sqlite-devel.x86_64 # for some R libraries
      - tbb-devel.x86_64 # for flexbar
      - udunits2-devel.x86_64 # for some R libraries
      - wget.x86_64
      - xorg-x11-xauth.x86_64 # or else X11 forwarding doesn't work
      - reptyr.x86_64 # re-parent a running process
      - parallel.noarch # needed by roary
    state: present
  when: ansible_distribution_major_version is version('8', '==')
  tags: packages

# Previously nvtop was not packaged in EPEL so we compiled it as an environment
# module. As of CentOS Stream 8 it is in EPEL and is more up to date than the
# one I had compiled manually.
- name: Install nvtop on compute06
  ansible.builtin.package:
    name: nvtop
    state: present
  when: inventory_hostname == 'compute06'
  tags: packages

# TODO: find a way to run this on Addis compute
- name: Clone environment modules
  ansible.builtin.git:
  when: "'nairobi_compute' in group_names"
    repo: https://github.com/ilri/hpc-environment-modules.git
    dest: /etc/modulefiles/ilri
    version: master
  tags: modules

# TODO: find a way to run this on Addis compute
- name: Copy ilri profile script
  ansible.builtin.template:
  when: "'nairobi_compute' in group_names"
    src: z-ilri.sh.j2
    dest: /etc/profile.d/z-ilri.sh
    owner: root
    group: root
    mode: "0644"
  tags: profile

- name: Copy limits configuration
  ansible.builtin.template:
    src: 90-ilri.conf.j2
    dest: /etc/security/limits.d/90-ilri.conf
    owner: root
    group: root
    mode: "0644"
  tags: limits

- name: Remove irqbalance
  ansible.builtin.package:
    name: irqbalance
    state: absent
  tags: irqbalance

- name: Configure ILRI ssh_config overrides
  ansible.builtin.template:
    src: etc/ssh/ssh_config.d/01-ilri.conf.j2
    dest: /etc/ssh/ssh_config.d/01-ilri.conf
    owner: root
    group: root
    mode: "0644"
  tags: ssh-config

- name: Set sticky bit on local scratch
  ansible.builtin.file:
    path: "{{ local_scratch }}"
    group: root
    owner: root
    mode: "01777"
    state: directory
  when: local_scratch is defined
  tags: scratch

- name: Add systemd-tmpfiles config for scratch
  ansible.builtin.template:
    src: etc/tmpfiles.d/scratch.conf.j2
    dest: /etc/tmpfiles.d/scratch.conf
    owner: root
    group: root
    mode: "0644"
  when: local_scratch is defined
  tags: scratch

# Keep 12 months of logins instead of 1
- name: Configure logrotate for wtmp
  ansible.builtin.lineinfile:
    path: /etc/logrotate.d/wtmp
    regexp: ^\s+rotate 1$
    line: "    rotate 12"
    state: present

# Keep 12 months of failed logins instead of 1
- name: Configure logrotate for btmp
  ansible.builtin.lineinfile:
    path: /etc/logrotate.d/btmp
    regexp: ^\s+rotate 1$
    line: "    rotate 12"
    state: present

# vim: set sw=2 ts=2:
