---

- name: Install extra packages
  yum: name={{ item }} state=present
  with_items:
    - environment-modules
    - xauth # or else X11 forwarding doesn't work
    - xeyes # to test x11 :)
    - libgomp # for R
    - libgfortran # for R
    - libicu # for R
    - libXtst # for some X apps like CLC Genomics
    - gsl # for fastSTRUCTURE
    - emacs
    - perl-parent # for some BioPerl scripts
    - java-1.8.0-openjdk # for lots of stuff
    - libtool-ltdl.x86_64 # for pandaseq/2.7
    - screen #terminal window manager
    - openblas.x86_64 #for scipy
    - compat-libstdc++-33.x86_64 #for libstdc++.so.5
    - proj.x86_64 #for libproj.so.0
    - gdal.x86_64 #for libgdal.so.1
    - libstdc++.i686 # for 32-bit binaries
    - gnuplot.x86_64
    - mailx.x86_64
    - pandoc.x86_64
    - argtable.x86_64 # for clustalo
    - boost-iostreams.x86_64 # for augustus
    - boost-devel.x86_64 # for augustus
    - tbb-devel.x86_64 # for flexbar
    - lapack.x86_64 # for presto
    - tmpwatch.x86_64
    - htop
    - nano
    - unzip
    - wget
    - perl-Text-Soundex.x86_64 # for RepeatMasker

- name: Install extra packages for Circos
  yum: name={{ item }} state=present
  with_items:
    - perl-Clone.x86_64
    - perl-Config-General.noarch
    - perl-Font-TTF.noarch
    - perl-Readonly.noarch
    - perl-Regexp-Common.noarch
    - perl-Text-Format.noarch
    - perl-GD.x86_64
    - perl-Params-Validate.x86_64

- name: Install extra packages for wise (dep of Cegma)
  yum: name={{ item }} state=present
  with_items:
    - glib.x86_64

- name: Install extra packages on CentOS 7
  yum: name={{ item }} state=present
  when: ansible_distribution_major_version | version_compare('7', '==')
  with_items:
    - libpng12.x86_64 # for pre-compiled blat binary
    - xz-compat-libs.x86_64 # for samtools/1.5 compiled on CentOS 6

# vim: set sw=2 ts=2:
