---

- name: Create slurm group
  group: name=slurm system=yes state=present gid=490

- name: Create slurm user
  user: name=slurm system=yes state=present createhome=no uid=490 group=slurm

- name: Install slurm
  yum: name={{ item }} state=present
  with_items:
    - slurm
    - slurm-slurmd
    - slurm-devel
    - slurm-munge
    - slurm-spank-x11 # for X11 support in slurm
    - munge
  tags: packages

- name: Copy slurm config
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  notify: restart slurmd

- name: Create slurm log dir
  file: path=/var/log/slurm owner=slurm group=slurm mode=0755 state=directory
  notify: restart slurmd

- name: Copy munge key
  copy: src=munge.key dest=/etc/munge/munge.key mode=0600 owner=munge group=munge
  notify: restart munge

- name: Start and enable munge
  systemd: name=munge state=started enabled=yes

- name: Start and enable slurmd
  when: inventory_hostname != slurm_head_node
  systemd: name=slurmd state=started enabled=yes

- name: Copy spank x11 config
  copy: src={{ item }} dest=/etc/slurm/{{ item }} mode=0644
  with_items:
    - plugstack.conf
    - plugstack.conf.d/x11.conf.example

# vim: set sw=2 ts=2:
