---

- name: Create slurm group
  ansible.builtin.group:
    name: slurm
    system: true
    state: present
    gid: 490

- name: Create slurm user
  ansible.builtin.user:
    name: slurm
    system: true
    state: present
    createhome: false
    uid: 490
    group: slurm

- name: Install slurm
  ansible.builtin.package:
    name:
      - slurm
      - slurm-slurmd
      - slurm-devel
      - slurm-pam_slurm
      - slurm-example-configs
      - munge
    state: latest
  tags: packages

- name: Copy slurm.conf
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart slurmdbd
    - restart slurmctld
    - restart slurmd

- name: Configure logrotate for slurm
  ansible.builtin.template:
    src: etc/logrotate.d/slurm.j2
    dest: /etc/logrotate.d/slurm
    owner: root
    group: root
    mode: 0644

- name: Copy extra slurm configs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 'etc/pam.d/slurm', dest: '/etc/pam.d/slurm'}
    - { src: 'etc/slurm/cgroup.conf', dest: '/etc/slurm/cgroup.conf'}
  notify:
    - restart slurmdbd
    - restart slurmctld
    - restart slurmd

- name: Copy gres.conf on compute06
  ansible.builtin.copy:
    src: etc/slurm/gres.conf
    dest: /etc/slurm/gres.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == 'compute06'
  notify:
    - restart slurmdbd
    - restart slurmctld
    - restart slurmd

- name: Create slurm directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
    mode: 0755
    state: directory
  loop:
    - /var/log/slurm
    - /var/spool/slurmd
  notify:
    - restart slurmdbd
    - restart slurmctld
    - restart slurmd

- name: Create slurmctld directory on head node
  ansible.builtin.file:
    path: /var/spool/slurmctld
    owner: slurm
    group: slurm
    mode: 0755
    state: directory
  when: inventory_hostname == slurm_head_node
  notify: restart slurmctld

- name: Copy munge key
  ansible.builtin.copy:
    src: munge.key
    dest: /etc/munge/munge.key
    mode: 0600
    owner: munge
    group: munge
  notify: restart munge

- name: Start and enable munge
  ansible.builtin.systemd:
    name: munge
    state: started
    enabled: true

# don't start slurmd on the head node just yet, because it technically needs to
# have the slurmdbd service started first and we don't check that.
- name: Start and enable slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: started
    enabled: true
  when: inventory_hostname != slurm_head_node

# vim: set sw=2 ts=2:
