---

- name: Create slurm group
  group: name=slurm system=yes state=present gid=490

- name: Create slurm user
  user: name=slurm system=yes state=present createhome=no uid=490 group=slurm

- name: Set slurm packages
  set_fact:
    slurm_packages:
      - slurm
      - slurm-slurmd
      - slurm-devel
      - slurm-pam_slurm
      - slurm-example-configs
      - munge

- name: Install slurm
  yum: name={{ slurm_packages }} state=present
  tags: packages

- name: Copy slurm.conf
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  notify: restart slurmd

- name: Copy extra slurm configs
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  loop:
    - { src: 'etc/pam.d/slurm', dest: '/etc/pam.d/slurm'}
    - { src: 'etc/slurm/cgroup.conf', dest: '/etc/slurm/cgroup.conf'}
  notify: restart slurmd

- name: Create slurm directories
  file: path={{ item }} owner=slurm group=slurm mode=0755 state=directory
  loop:
    - /var/log/slurm
    - /var/spool/slurmd
  notify: restart slurmd

- name: Copy munge key
  copy: src=munge.key dest=/etc/munge/munge.key mode=0600 owner=munge group=munge
  notify: restart munge

- name: Start and enable munge
  systemd: name=munge state=started enabled=yes

# don't start slurmd on the head node just yet, because it technically needs to
# have the slurmdbd service started first and we don't check that.
- name: Start and enable slurmd
  when: inventory_hostname != slurm_head_node
  systemd: name=slurmd state=started enabled=yes

# vim: set sw=2 ts=2:
