---

- name: Create slurm group
  group: name=slurm system=yes state=present gid=490

- name: Create slurm user
  user: name=slurm system=yes state=present createhome=no uid=490 group=slurm

- name: Install slurm
  when: ansible_distribution == 'CentOS' and inventory_hostname != 'hpc'
  yum: name={{ item }} state=present
  with_items:
    - slurm
    - slurm-devel
    - slurm-munge
    - slurm-spank-x11 # for X11 support in slurm
    - munge
  tags: packages

- name: Copy slurm config to CentOS 6 hosts
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  when: ansible_distribution_major_version == '6'
  notify: restart slurm on CentOS 6 hosts

- name: Copy slurm config to CentOS 7 hosts
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  when: ansible_distribution_major_version == '7'
  notify: restart slurm on CentOS 7 hosts

- name: Create slurm log dir on CentOS 7 hosts
  when: ansible_distribution_major_version == '7'
  notify: restart slurm on CentOS 7 hosts
  file: path=/var/log/slurm owner=slurm group=slurm mode=0755 state=directory

- name: Copy munge key
  copy: src=munge.key dest=/etc/munge/munge.key mode=0600 owner=munge group=munge
  notify: restart munge

- name: Start & enable munge
  service: name=munge state=started enabled=yes

- name: Start & enable slurm on CentOS 6 hosts
  when: ansible_distribution_major_version | version_compare('6', '==')
  service: name=slurm state=started enabled=yes

- name: Start & enable slurmctld on CentOS 7 head node
  when: inventory_hostname == slurm_head_node and ansible_distribution_major_version == '7'
  service: name=slurmctld state=started enabled=yes

- name: Start & enable slurmd on CentOS 7 compute nodes
  when: ansible_distribution_major_version == '7'
  service: name=slurmd state=started enabled=yes

- name: Copy spank x11 config
  copy: src={{ item }} dest=/etc/slurm/{{ item }} mode=0644
  with_items:
    - plugstack.conf
    - plugstack.conf.d/x11.conf.example

# vim: set sw=2 ts=2:
