---

- name: Create slurm group
  group: name=slurm system=yes state=present gid=490

- name: Create slurm user
  user: name=slurm system=yes state=present createhome=no uid=490 group=slurm

- name: Install slurm
  when: ansible_distribution == 'CentOS' and inventory_hostname != 'hpc'
  yum: name={{ item }} state=present
  with_items:
    - slurm
    - slurm-devel
    - slurm-munge
    - slurm-spank-x11 # for X11 support in slurm
    - munge

- name: Copy slurm config
  template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root group=root mode=0644
  notify: restart slurm

- name: Copy munge key
  copy: src=munge.key dest=/etc/munge/munge.key mode=0600 owner=munge group=munge
  notify: restart munge

- name: Start & enable munge
  service: name=munge state=started enabled=yes

- name: Start & enable slurm
  service: name=slurm state=started enabled=yes
  tags: slurm

- name: Copy spank x11 config
  copy: src={{ item }} dest=/etc/slurm/{{ item }} mode=0644
  with_items:
    - plugstack.conf
    - plugstack.conf.d/x11.conf.example

# vim: set sw=2 ts=2:
