---

solr_version: 8.11.2
solr_tarball: solr-{{ solr_version }}.tgz
solr_mirror_url: https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/{{ solr_tarball }}
solr_sha256sum: 54d6ebd392942f0798a60d50a910e26794b2c344ee97c2d9b50e678a7066d3a6
solr_prefix_dir: /opt
solr_install_dir: /opt/solr-{{ solr_version }}
solr_home_dir: /var/solr
solr_port: 8983
solr_user: solr
solr_group: solr
solr_user_homedir: /home/{{ solr_user }}

# For newer Solr using systemd service.
solr_heap: 1g
# For older Solr using solr.in.sh.
solr_java_mem: "-Xms1024m -Xmx1024m"
