---
# For now this only installs the Certbot Let's Encrypt client, installs some
# dependencies, and configures the systemd timer for certificate renewals.
#
# To use it, add `use_letsencrypt: True` to a host's variables and run the
# "letsencrypt" tag.

# On Ubuntu 20.04 it is no longer recommended/supported to use the standalone
# certbot-auto so I guess we need to use the one from the repositories.
- block:
  - name: Install certbot (Ubuntu 20.04)
    apt: name=certbot state=present update_cache=yes

  - name: Create Let's Encrypt hooks directories
    file: path={{ item }} state=directory owner=root group=root mode=0755
    with_items:
      - /etc/letsencrypt/renewal-hooks/pre
      - /etc/letsencrypt/renewal-hooks/post

  - name: Copy certbot post and pre hooks for nginx
    copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0755
    with_items:
      - { src: 'stop-nginx.sh', dest: '/etc/letsencrypt/renewal-hooks/pre/stop-nginx.sh' }
      - { src: 'start-nginx.sh', dest: '/etc/letsencrypt/renewal-hooks/post/start-nginx.sh' }
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '==')
  tags: letsencrypt

# vim: set ts=2 sw=2:
