---
- name: Install DSpace deps
  apt: pkg={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - tomcat7
    - tomcat7-admin
    - ant
    - maven
    - libtcnative-1
    - poppler-utils # for media filter
    - python-psycopg2 # for ansible postgres modules
    - postgresql-contrib # for DSpace functions
    - imagemagick # for DSpace 5 thumbnails
    - ghostscript # for DSpace 5 PDF thumbnails
  tags: packages

- name: Install DSpace 5 Mirage 2 build deps
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - libyaml-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - make
    - libtool
    - bison
    - pkg-config
    - libffi-dev
    - gawk
    - g++
    - libreadline6-dev
    - zlib1g-dev
    - libssl-dev
    - libsqlite3-dev
  tags: packages

- name: Add Oracle Java PPA
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags: java

- name: Accept Oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: java

- name: Install Oracle Java
  apt: pkg=oracle-java7-installer state=present
  tags: java

- include: nginx.yml
  tags: nginx

- name: Set Tomcat user's shell
  user: name=tomcat7 shell=/bin/bash
  tags: tomcat

- name: Allow Tomcat user to write to ~tomcat7
  file: path=/usr/share/tomcat7 owner=tomcat7 group=tomcat7
  tags: tomcat

- name: Touch Tomcat user's .profile
  file: path=/usr/share/tomcat7/.profile state=touch owner=tomcat7 group=tomcat7 mode=0644
  tags: tomcat

- name: Set tomcat7 defaults
  template: src=tomcat/tomcat7.j2 dest=/etc/default/tomcat7 owner=root group=root mode=0644
  notify:
    - restart tomcat7
  tags: tomcat

- name: Copy Tomcat config(s)
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: 'tomcat/server.xml.j2', dest: '/etc/tomcat7/server.xml', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'tomcat/tomcat-users.xml.j2', dest: '/etc/tomcat7/tomcat-users.xml', owner: 'root', group: 'tomcat7', mode: '0640' }
  notify:
    - restart tomcat7
  tags: tomcat

- name: Prepare Tomcat web application contexts
  template: src=tomcat/context.xml.j2 dest={{ item.context_path }}
  with_items: dspace_webapps
  when: dspace_webapps is defined
  notify:
    - restart tomcat7
  tags: tomcat

- name: Enable Tomcat
  service: name=tomcat7 enabled=yes
  tags: tomcat

- name: Prepare tomcat7 home folder
  file: dest={{ item.dest }} state={{ item.state }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { dest: '/usr/share/tomcat7/.m2', state: 'directory', owner: 'tomcat7', group: 'tomcat7', mode: '750' }
    - { dest: '/usr/share/tomcat7/src/git/DSpace', state: 'directory', owner: 'tomcat7', group: 'tomcat7', mode: '755' }
  tags: tomcat

- name: Configure rotation for Tomcat access logs
  copy: src=etc/logrotate.d/tomcat7-access_logs dest=/etc/logrotate.d/tomcat7-access_logs owner=root group=root mode=0644
  tags: tomcat

- name: Copy maven settings
  template: src=m2/settings.xml.j2 dest=/usr/share/tomcat7/.m2/settings.xml owner=tomcat7 group=tomcat7 mode=640
  when: maven_username is defined and maven_password is defined

- name: Clone DSpace repository
  git: repo={{ dspace_git_repo }} dest=/usr/share/tomcat7/src/git/DSpace version={{ dspace_git_branch }}
  sudo_user: tomcat7

- name: Create DSpace postgres user
  postgresql_user: name={{ dspace_db_user }} password={{ dspace_db_password }}
  sudo_user: postgres
  tags: postgres

- name: Create DSpace postgres database
  postgresql_db: name={{ dspace_db_name }} encoding='UTF-8' template='template0' owner={{ dspace_db_user }}
  sudo_user: postgres
  tags: postgres

- name: Set up cron job for Handle server
  template: src=dspace-handle-server.j2 dest=/etc/cron.d/dspace-handle-server owner=root group=root mode=644

- name: Create DSpace install directory
  file: path={{ dspace_root }} owner=tomcat7 group=tomcat7 mode=0755 state=directory

# vim: set sw=2 ts=2:
