---
- name: Install DSpace deps
  apt: pkg={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - tomcat{{ tomcat_version_major }}
    - tomcat{{ tomcat_version_major }}-admin
    - ant
    - maven
    - libtcnative-1
    - poppler-utils # for media filter
    - python-psycopg2 # for ansible postgres modules
    - postgresql-contrib-{{ pg_version }} # for DSpace functions
    - imagemagick # for DSpace 5 thumbnails
    - ghostscript # for DSpace 5 PDF thumbnails
  tags: packages

- name: Install DSpace 5 Mirage 2 build deps
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - libyaml-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - make
    - libtool
    - bison
    - pkg-config
    - libffi-dev
    - gawk
    - g++
    - libreadline6-dev
    - zlib1g-dev
    - libssl-dev
    - libsqlite3-dev
  tags: packages

- name: Add Oracle Java PPA
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags: java

- name: Accept Oracle license
  debconf: name='oracle-java{{ java_version_major }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: java

- name: Install Oracle Java
  apt: pkg=oracle-java{{ java_version_major }}-installer state=present
  tags: java

- include: nginx.yml
  tags: nginx

- name: Set Tomcat user's shell
  user: name={{ tomcat_user }} shell=/bin/bash
  tags: tomcat

- name: Allow Tomcat user to write to ~tomcat7
  file: path={{ tomcat_user_home }} owner={{ tomcat_user }} group={{ tomcat_group }}
  tags: tomcat

- name: Touch Tomcat user's .profile
  file: path={{ tomcat_user_home }}/.profile state=touch owner={{ tomcat_user }} group={{ tomcat_group }} mode=0644
  tags: tomcat

- name: Set Tomcat defaults
  template: src=tomcat/defaults-tomcat{{ tomcat_version_major }}.j2 dest=/etc/default/tomcat{{ tomcat_version_major }} owner=root group=root mode=0644
  notify:
    - restart tomcat{{ tomcat_version_major }}
  tags: tomcat

- name: Copy Tomcat config(s)
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: 'tomcat/server-tomcat{{ tomcat_version_major }}.xml.j2', dest: '/etc/tomcat{{ tomcat_version_major }}/server.xml', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'tomcat/tomcat-users.xml.j2', dest: '/etc/tomcat{{ tomcat_version_major }}/tomcat-users.xml', owner: 'root', group: '{{ tomcat_user }}', mode: '0640' }
  notify:
    - restart tomcat{{ tomcat_version_major }}
  tags: tomcat

- name: Prepare Tomcat web application contexts
  template: src=tomcat/context.xml.j2 dest={{ item.context_path }}
  with_items: "{{ dspace_webapps }}"
  when: dspace_webapps is defined
  notify:
    - restart tomcat{{ tomcat_version_major }}
  tags: tomcat

- name: Enable Tomcat
  service: name=tomcat{{ tomcat_version_major }} enabled=yes
  tags: tomcat

- name: Prepare tomcat7 home folder
  file: dest={{ item.dest }} state={{ item.state }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { dest: '{{ tomcat_user_home }}/.m2', state: 'directory', owner: '{{ tomcat_user }}', group: '{{ tomcat_group }}', mode: '750' }
    - { dest: '{{ tomcat_user_home }}/src/git/DSpace', state: 'directory', owner: '{{ tomcat_user }}', group: '{{ tomcat_group }}', mode: '755' }
  tags: tomcat

- name: Configure rotation for Tomcat access logs
  template: src=tomcat/logrotate-access_logs.j2 dest=/etc/logrotate.d/tomcat-access_logs owner=root group=root mode=0644
  tags: tomcat

# Idempotency: remove old versions of the script (delete this task after all hosts have run it)
- name: Delete old log rotate script(s)
  file: dest={{ item }} state=absent
  with_items:
    - /etc/logrotate.d/tomcat7-access_logs
    - /etc/logrotate.d/tomcat8-access_logs
  tags: tomcat

- name: Set open file limits for tomcat user
  template: src=tomcat/limits.conf.j2 dest=/etc/security/limits.d/90-tomcat.conf owner=root group=root mode=0644
  tags: tomcat

# Idempotency: remove old versions of the config (delete this task after all hosts have run it)
- name: Delete old limits config(s)
  file: dest={{ item }} state=absent
  with_items:
    - /etc/security/limits.d/90-tomcat7.conf
    - /etc/security/limits.d/90-tomcat8.conf
  tags: tomcat

- name: Copy maven settings
  template: src=m2/settings.xml.j2 dest={{ tomcat_user_home }}/.m2/settings.xml owner=tomcat8 group=tomcat8 mode=640
  when: maven_username is defined and maven_password is defined

- name: Clone DSpace repository
  git: repo={{ dspace_git_repo }} dest={{ tomcat_user_home }}/src/git/DSpace version={{ dspace_git_branch }}
  become_user: '{{ tomcat_user }}'

- name: Create DSpace postgres user
  postgresql_user: name={{ dspace_db_user }} password={{ dspace_db_password }}
  become_user: postgres
  tags: postgres

- name: Create DSpace postgres database
  postgresql_db: name={{ dspace_db_name }} encoding='UTF-8' template='template0' owner={{ dspace_db_user }}
  become_user: postgres
  tags: postgres

- name: Set up cron job for Handle server
  template: src=dspace-handle-server.j2 dest=/etc/cron.d/dspace-handle-server owner=root group=root mode=644

- name: Create DSpace install directory
  file: path={{ dspace_root }} owner={{ tomcat_user }} group={{ tomcat_group }} mode=0755 state=directory

# vim: set sw=2 ts=2:
