---
# Explicitly install OpenJDK first in a separate transaction so that Ubuntu
# doesn't pull in other Javas when we install ant, maven, etc.
- name: Install OpenJDK
  ansible.builtin.apt:
    pkg: openjdk-{{ java_version_major }}-jdk-headless
    state: present
    install_recommends: false
    cache_valid_time: 3600

- name: Set OpenJDK 8 as default java
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: java_version_major == 8

- name: Set OpenJDK 17 as default java
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
  when: java_version_major == 17

# 2020-02-23: Fix issue with JFreeChart in Atmire CUA
# see https://code-maven.com/slides/jenkins-intro/no-graph-error
- name: Disable OpenJDK assistive technologies
  ansible.builtin.lineinfile:
    path: /etc/java-8-openjdk/accessibility.properties
    regexp: ^assistive_technologies=org.GNOME.Accessibility.AtkWrapper$
    line: "#assistive_technologies=org.GNOME.Accessibility.AtkWrapper"
    state: present
  when: java_version_major == 8

# 2021-06-30: Fix slow Tomcat startup due to blocking /dev/random
# tomcat7[30294]: WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [111,733] milliseconds.
- name: Use /dev/urandom for JVM SecureRandom
  ansible.builtin.lineinfile:
    path: /etc/java-{{ java_version_major }}-openjdk/security/java.security
    regexp: ^securerandom.source=file:/dev/random$
    line: securerandom.source=file:/dev/urandom
    state: present

# vim: set sw=2 ts=2:
