---
# Explicitly install OpenJDK first in a separate transaction so that Ubuntu
# doesn't pull in other Javas when we install ant, maven, etc.
- name: Install OpenJDK
  ansible.builtin.apt:
    pkg: openjdk-{{ java_version_major }}-jdk-headless
    state: present
    install_recommends: false
    cache_valid_time: 3600

- name: Set OpenJDK 17 as default java
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
  when: java_version_major is version('17', '==')

# vim: set sw=2 ts=2:
