---
- name: Install Solr deps
  apt: name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - unzip
    - tar
  tags: packages

- name: Add Oracle Java PPA
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags:
    - java
    - packages

- name: Accept Oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags:
    - java
    - packages

- name: Install Oracle Java 8
  apt: name=oracle-java8-installer state=present update_cache=yes
  tags:
    - java
    - packages

- include: solr.yml
  tags: solr

# vim: set ts=2 sw=2:
