---
- name: Install Ansible unarchive dependencies
  ansible.builtin.package:
    name: ['unzip', 'tar']
    state: present
    install_recommends: no
    cache_valid_time: 3600
  tags: packages

- name: Install OpenJDK 8
  ansible.builtin.package:
    name: openjdk-8-jre-headless
    state: present
    install_recommends: no
  when: ansible_distribution_version is version('16.04', '>=')
  tags:
    - java
    - packages

- name: Configure Solr
  ansible.builtin.import_tasks: solr.yml
  tags: solr

# vim: set ts=2 sw=2:
