---
- name: Install Ansible unarchive dependencies
  ansible.builtin.package:
    name: ['unzip', 'tar']
    state: present
    install_recommends: false
    cache_valid_time: 3600
  tags: packages

- name: Install OpenJDK 8
  ansible.builtin.package:
    name: openjdk-8-jre-headless
    state: present
    install_recommends: false
  when: ansible_distribution_version is version('22.04', '<')
  tags:
    - java
    - packages

- name: Install OpenJDK 17
  ansible.builtin.package:
    name: openjdk-17-jre-headless
    state: present
    install_recommends: false
  when: ansible_distribution_version is version('22.04', '>=')
  tags:
    - java
    - packages

- name: Configure Solr
  ansible.builtin.import_tasks: solr.yml
  when: ansible_distribution_version is version('22.04', '>=')
  tags: solr

# vim: set ts=2 sw=2:
