---
- name: Install Solr deps
  apt: name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - tomcat7
    - tomcat7-admin
    - libtcnative-1
  tags: packages

- name: Add Oracle Java PPA
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags: java

- name: Accept Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  tags: java

- name: Install Oracle Java
  apt: name=oracle-java7-installer state=present update_cache=yes
  tags: java

- name: Set tomcat7 defaults
  template: src=tomcat/tomcat7.j2 dest=/etc/default/tomcat7 owner=root group=root mode=0644
  notify:
    - restart tomcat7
  tags: tomcat

- name: Copy Tomcat config(s)
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: 'tomcat/server.xml.j2', dest: '/etc/tomcat7/server.xml', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'tomcat/tomcat-users.xml.j2', dest: '/etc/tomcat7/tomcat-users.xml', owner: 'root', group: 'tomcat7', mode: '0640' }
  notify:
    - restart tomcat7
  tags: tomcat

- name: Start & enable tomcat7 service
  service: name=tomcat7 state=started enabled=yes
  tags: tomcat

- include: solr.yml
  tags: solr

# vim: set ts=2 sw=2:
