---
- name: Install Ansible unarchive dependencies
  apt: name={{ item }} state=present install_recommends=no cache_valid_time=3600
  loop:
    - unzip
    - tar
  tags: packages

- name: Install OpenJDK 7
  apt:
    name: openjdk-7-jre-headless
    state: present
    install_recommends: no
  when: ansible_distribution_version is version('14.04', '==')
  tags:
    - java
    - packages

- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jre-headless
    state: present
    install_recommends: no
  when: ansible_distribution_version is version('16.04', '>=')
  tags:
    - java
    - packages

- name: Configure Solr
  import_tasks: solr.yml
  tags: solr

# vim: set ts=2 sw=2:
