---

- name: Get Solr tarball
  get_url: url={{ solr_mirror_url }} dest={{ solr_prefix_dir }}/{{ solr_tarball }} sha256sum={{ solr_sha256sum }}
  register: get_url_result

- name: Unpack Solr tarball
  unarchive: src={{ solr_prefix_dir }}/{{ solr_tarball }} dest={{ solr_prefix_dir }} creates={{ solr_prefix_dir }}/solr-{{ solr_version }} copy=no
  when: get_url_result|changed

# Not sure if we need all the libs
# See: http://duntuk.com/how-install-apache-solr-46-apache-tomcat-7-use-drupal
# See: https://cwiki.apache.org/confluence/display/solr/Running+Solr+on+Tomcat
- name: Copy Solr stuff to Tomcat classpath
  shell: cp {{ item }} /usr/share/tomcat7/lib
  with_items:
    - "{{ solr_prefix_dir }}/solr-{{ solr_version }}/example/lib/ext/*.jar"
    - "{{ solr_prefix_dir }}/solr-{{ solr_version }}/dist/solrj-lib/*.jar"
    - "{{ solr_prefix_dir }}/solr-{{ solr_version }}/example/resources/log4j.properties"

- name: Create Solr home
  command: cp -r {{ solr_prefix_dir }}/solr-{{ solr_version }}/example/solr {{ solr_home }} creates={{ solr_home }}

# create more Solr cores?
# See: https://wiki.apache.org/solr/Core%20Discovery%20%284.4%20and%20beyond%29
- include: solr-cores.yml
  when: solr_cores is defined

- name: Fix permissions on Solr home
  file: dest={{ solr_home }} state=directory owner=tomcat7 group=tomcat7 recurse=yes

# Single Solr context, but could do more in the future (instances are more isolated than cores)
# See: https://cwiki.apache.org/confluence/display/solr/Running+Solr+on+Tomcat
- name: Create Solr Tomcat context
  template: src=tomcat/context.xml.j2 dest=/etc/tomcat7/Catalina/localhost/solr.xml owner=tomcat7 group=tomcat7

- name: Create Solr log directory
  file: dest={{ solr_log_dir }} state=directory owner=tomcat7 group=tomcat7 mode=0755

- name: Re-configure Solr logging
  lineinfile: dest=/usr/share/tomcat7/lib/log4j.properties regexp="^solr.log=logs/" line=solr.log={{ solr_log_dir }}

- name: Configure logrotate
  template: src=solr.j2 dest=/etc/logrotate.d/solr owner=root group=root mode=0644

# vim: set ts=2 sw=2:
