---

- name: Create Solr core data directory
  ansible.builtin.file:
    dest: "{{ solr_home_dir }}/data/{{ item }}/data/index"
    state: directory
    mode: 0755
  loop: "{{ solr_cores }}"
  notify: restart solr
  tags: solr-cores

- name: Create Solr core configuration directory
  ansible.builtin.file:
    dest: "{{ solr_home_dir }}/data/{{ item }}/conf"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
    mode: 0755
  loop: "{{ solr_cores }}"
  notify: restart solr
  tags: solr-cores

- name: Populate Solr core configuration directory
  ansible.posix.synchronize:
    src: "{{ solr_install_dir }}/server/solr/configsets/basic_configs/conf/"
    dest: "{{ solr_home_dir }}/data/{{ item }}/conf/"
  delegate_to: localhost
  loop: "{{ solr_cores }}"
  notify: restart solr
  tags: solr-cores

- name: Create core.properties placeholder
  ansible.builtin.file:
    dest: "{{ solr_home_dir }}/data/{{ item }}/core.properties"
    state: touch
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
    mode: 0644
  loop: "{{ solr_cores }}"
  notify: restart solr
  tags: solr-cores

# vim: set ts=2 sw=2:
