---
# file: roles/dspace/handlers/main.yml

- name: restart nginx
  systemd: name=nginx state=restarted

- name: reload nginx
  systemd: name=nginx state=reloaded

- name: restart tomcat7
  systemd: name=tomcat7 state=restarted

- name: restart tomcat8
  systemd: name=tomcat8 state=restarted

- name: reload postgresql
  systemd: name=postgresql state=reloaded

- name: restart dspace-statistics-api
  systemd: name=dspace-statistics-api state=restarted
