---
# file: roles/dspace/handlers/main.yml
#
# Note: Ansible handlers are global so I technically shouldn't need an nginx
# handler here (there is one in the web role), but I am getting an error:
#
#   ERROR! The requested handler 'web: reload nginx' was not found in either the main handlers list nor in the listening handlers list
#
# So for now I will duplicate it here.

- name: restart tomcat7
  ansible.builtin.systemd:
    name: tomcat7
    state: restarted

- name: restart tomcat8
  ansible.builtin.systemd:
    name: tomcat8
    state: restarted

- name: restart dspace-statistics-api
  ansible.builtin.systemd:
    name: dspace-statistics-api
    state: restarted

# When configs or TLS certificates change
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
