---
# file: roles/dspace/handlers/main.yml
#
# Note: because Ansible handlers are global, there are no nginx handlers here.
# They are in the web role.
#

- name: restart tomcat7
  ansible.builtin.systemd:
    name: tomcat7
    state: restarted

- name: restart tomcat8
  ansible.builtin.systemd:
    name: tomcat8
    state: restarted

- name: restart dspace-statistics-api
  ansible.builtin.systemd:
    name: dspace-statistics-api
    state: restarted
