---
- name: Remove cron-apt config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cron-apt/config
    - /etc/cron-apt/action.d/3-download
    - /etc/apt/security.sources.list

- name: Remove cron-apt
  ansible.builtin.package:
    name: cron-apt
    state: absent

# vim: set ts=2 sw=2:
