---
# Use iptables service on CentOS 6
# Use firewalld on CentOS >= 7

- block:
  - name: Copy /etc/sysconfig/iptables
    when: ansible_distribution_major_version is version_compare('6', '==')
    template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root mode=0600
    notify:
      - restart iptables

  - name: Copy /etc/sysconfig/ip6tables
    when: ansible_distribution_major_version is version_compare('6', '==')
    template: src=ip6tables.j2 dest=/etc/sysconfig/ip6tables owner=root group=root mode=0600
    notify:
      - restart ip6tables

  - name: Set CentOS firewall packages
    set_fact:
      centos_firewall_packages:
        - tidy
        - fail2ban

  - name: Install firewall packages
    when: ansible_distribution_major_version is version_compare('7', '>=')
    yum: name={{ centos_firewall_packages }} state=present
    tags: packages

# firewalld developers only claim nftables support with nftables >= 0.9.3
# See: https://firewalld.org/2019/09/libnftables-JSON
  - name: Use iptables backend in firewalld
    when: ansible_distribution_major_version is version_compare('8', '==')
    lineinfile:
      dest: /etc/firewalld/firewalld.conf
      regexp: '^FirewallBackend=nftables$'
      line: 'FirewallBackend=iptables'
    notify:
      - restart firewalld

# firewalld seems to have an issue with iptables 1.8.2. Using individual calls
# seems to work around it.
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931722
  - name: Use individual iptables calls
    when: ansible_distribution_major_version is version_compare('8', '==')
    lineinfile:
      dest: /etc/firewalld/firewalld.conf
      regexp: '^IndividualCalls=no$'
      line: 'IndividualCalls=yes'
    notify:
      - restart firewalld

# 2019-12-10: fail2ban does not currently work with SELinux on CentOS 8, ie:
#
#   SELinux is preventing /usr/lib/systemd/systemd from mounton access on the directory /run/systemd/unit-root/var/lib/fail2ban.
#   SELinux is preventing /usr/libexec/platform-python3.6 from using the nnp_transition access on a process.
#
# Set SELinux to permissive for now.
  - name: Disable selinux on CentOS 8
    when: ansible_distribution_major_version is version_compare('8', '==')
    selinux:
      state: permissive
    notify:
      - restart firewalld

  - name: Copy firewalld public zone file to /etc/firewalld/zones/public.xml
    when: ansible_distribution_major_version is version_compare('7', '>=')
    template: src=public.xml.j2 dest=/etc/firewalld/zones/public.xml owner=root mode=0600

  - name: Format public.xml firewalld zone file
    when: ansible_distribution_major_version is version_compare('7', '>=')
    command: tidy -xml -iq -m -w 0 /etc/firewalld/zones/public.xml
    notify:
      - restart firewalld

  - name: Copy ipsets of abusive IPs
    when: ansible_distribution_major_version is version_compare('7', '>=')
    copy: src={{ item }} dest=/etc/firewalld/ipsets/{{ item }} owner=root group=root mode=0600
    loop:
      - abusers-ipv4.xml
      - abusers-ipv6.xml
    notify:
      - restart firewalld

  - include_tasks: fail2ban.yml
    when: ansible_distribution_major_version is version_compare('7', '>=')
  tags: firewall

# vim: set sw=2 ts=2:
