---
# Use iptables-persistent on Debian 7 and firewalld on Debian 8.

- block:
  - name: Install iptables-persistent
    when: ansible_distribution_major_version is version('7', '==')
    apt: name=iptables-persistent state=present cache_valid_time=3600
    tags:
      - packages

  - name: Copy /etc/iptables/rules.v4
    when: ansible_distribution_major_version is version('7', '==')
    template: src=iptables.j2 dest=/etc/iptables/rules.v4 owner=root group=root mode=0600
    notify:
      - restart iptables-persistent

  - name: Copy /etc/iptables/rules.v6
    when: ansible_distribution_major_version is version('7', '==')
    template: src=ip6tables.j2 dest=/etc/iptables/rules.v6 owner=root group=root mode=0600
    notify:
      - restart iptables-persistent

  - name: Install firewalld
    when: ansible_distribution_major_version is version('8', '==')
    apt: name={{ item }} state=present
    loop:
      - firewalld
      - tidy
    tags: packages

  - name: Copy firewalld public zone file to /etc/firewalld/zones/public.xml
    when: ansible_distribution_major_version is version('8', '==')
    template: src=public.xml.j2 dest=/etc/firewalld/zones/public.xml owner=root mode=0600

  - name: Format public.xml firewalld zone file
    when: ansible_distribution_major_version is version('8', '==')
    command: tidy -xml -iq -m -w 0 /etc/firewalld/zones/public.xml
    notify:
      - restart firewalld

  - name: Remove iptables-persistent
    when: ansible_distribution_major_version is version('8', '==')
    apt: name=iptables-persistent state=absent
    tags: packages

  # remove old iptables rules and restart new firewall service to make sure its
  # state is as intended (ie, in case system was upgraded from Debian 7).
  - name: Remove old iptables rules
    when: ansible_distribution_major_version is version('8', '==')
    file: path={{ item }} state=absent
    loop:
      - /etc/iptables/rules.v4
      - /etc/iptables/rules.v6
    notify:
      - restart firewalld
  tags: firewall

# vim: set sw=2 ts=2:
