---

# Glaring fucking hack: skip the firewall on linode31 and hetzner02 because they
# run Docker and Docker doesn't work with nftables. We also ignore holstein be-
# cause it is running libvirtd, which has a hard depend on iptables.
- name: Configure firewall on Ubuntu
  ansible.builtin.include_tasks:
    file: firewall_Ubuntu.yml
    apply:
      tags:
        - firewall
  when:
    - ansible_distribution == 'Ubuntu'
    - inventory_hostname != 'linode31'
    - inventory_hostname != 'holstein'
    - inventory_hostname != 'hetzner02'
  tags: firewall

- name: Configure firewall on Debian
  ansible.builtin.include_tasks:
    file: firewall_Debian.yml
    apply:
      tags:
        - firewall
  when:
    - ansible_distribution == 'Debian'
  tags: firewall

- name: Configure firewall on CentOS
  ansible.builtin.include_tasks:
    file: firewall_CentOS.yml
    apply:
      tags:
        - firewall
  when: ansible_distribution == 'CentOS'
  tags: firewall

- name: Copy AbuseIPDB.com scripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - { 'src': scripts/parse_logs.py.j2, 'dest': /opt/ilri/scripts/parse_logs.py }
    - { 'src': scripts/report-ssh-abuseipdb.sh.j2, 'dest': /opt/ilri/scripts/report-ssh-abuseipdb.sh }
  tags: firewall

# vim: set sw=2 ts=2:
