---

# Glaring fucking hack: skip the firewall on linode20 and linode31 because they
# run Docker and Docker doesn't work with nftables. We also ignore holstein be-
# cause it is running libvirtd, which has a hard depend on iptables.
- include_tasks: firewall_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and
        inventory_hostname != 'linode20' and
        inventory_hostname != 'linode31' and
        inventory_hostname != 'holstein'
  tags: firewall

- include_tasks: firewall_Debian.yml
  when: ansible_distribution == 'Debian'
  tags: firewall

- include_tasks: firewall_CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags: firewall

- name: Copy AbuseIPDB.com script
  template:
    src: scripts/parse_logs.py.j2
    dest: /opt/ilri/scripts/parse_logs.py
    owner: root
    group: root
    mode: 0755

# vim: set sw=2 ts=2:
