---

- include_tasks: firewall_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: firewall

- include_tasks: firewall_Debian.yml
  when: ansible_distribution == 'Debian'
  tags: firewall

- include_tasks: firewall_CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags: firewall

# vim: set sw=2 ts=2:
