---
# Use iptables service on CentOS 6
# Use firewalld on CentOS 7
# Never run firewall rules on HPC

- name: Copy /etc/sysconfig/iptables
  when: inventory_hostname != 'hpc' and ansible_distribution_major_version == '6'
  template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root mode=0600
  notify:
    - restart iptables

- name: Copy /etc/sysconfig/ip6tables
  when: inventory_hostname != 'hpc' and ansible_distribution_major_version == '6'
  template: src=ip6tables.j2 dest=/etc/sysconfig/ip6tables owner=root group=root mode=0600
  notify:
    - restart ip6tables

- name: Install tidy
  when: ansible_distribution_major_version == '7'
  yum: name={{ item }} state=present
  with_items:
    - tidy

- name: Copy firewalld public zone file to /etc/firewalld/zones/public.xml
  when: inventory_hostname != 'hpc' and ansible_distribution_major_version == '7'
  template: src=public.xml.j2 dest=/etc/firewalld/zones/public.xml owner=root mode=0600

- name: Format public.xml firewalld zone file
  when: inventory_hostname != 'hpc' and ansible_distribution_major_version == '7'
  shell: tidy -xml -iq -m -w 0 /etc/firewalld/zones/public.xml
  notify:
    - restart firewalld

# vim: set sw=2 ts=2:
