---
# Use nftables on CentOS Stream 8

- name: Install firewall packages (CentOS Stream 8)
  when: ansible_distribution_major_version is version('8', '==')
  ansible.builtin.package:
    name:
      - nftables
      - sshguard
      - perl-Net-IP # for aggregate-cidr-addresses.pl
      - wget # for updating blocklists
    state: present
  tags: packages

# firewalld seems to be a part of the base distribution, but we don't need it.
- name: Remove firewalld (CentOS Stream 8)
  when: ansible_distribution_major_version is version('8', '==')
  ansible.builtin.package:
    name: firewalld
    state: absent
  tags: packages

- name: Configure nftables
  ansible.builtin.include_tasks: nftables.yml
  when: ansible_distribution_major_version is version('8', '==')

# TODO: re-evaluate this later, as no current CentOS versions run fail2ban
# without pulling in firewalld right now.
- name: Configure fail2ban
  ansible.builtin.include_tasks: fail2ban.yml
  when: ansible_distribution_major_version is version('7', '==')

# Use sshguard on CentOS Stream 8 because the fail2ban package has a hard dep
# on firewalld and we want to use nftables directly.
- name: Configure sshguard
  ansible.builtin.include_tasks: sshguard.yml
  when: ansible_distribution_major_version is version('8', '==')

# vim: set sw=2 ts=2:
