---

# Glaring fucking hack: skip the firewall on linode20 and linode31 because they
# run Docker and Docker doesn't work with nftables.
- include_tasks: firewall_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and
        inventory_hostname != 'linode20' and
        inventory_hostname != 'linode31'
  tags: firewall

- include_tasks: firewall_Debian.yml
  when: ansible_distribution == 'Debian'
  tags: firewall

- include_tasks: firewall_CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags: firewall

# vim: set sw=2 ts=2:
