---

- import_tasks: firewall_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: firewall_Debian.yml
  when: ansible_distribution == 'Debian'

- import_tasks: firewall_CentOS.yml
  when: ansible_distribution == 'CentOS'

# vim: set sw=2 ts=2:
