---
# Use iptables service on CentOS 6
# Use firewalld on CentOS 7

- block:
  - name: Copy /etc/sysconfig/iptables
    when: ansible_distribution_major_version is version_compare('6', '==')
    template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root mode=0600
    notify:
      - restart iptables

  - name: Copy /etc/sysconfig/ip6tables
    when: ansible_distribution_major_version is version_compare('6', '==')
    template: src=ip6tables.j2 dest=/etc/sysconfig/ip6tables owner=root group=root mode=0600
    notify:
      - restart ip6tables

  - name: Install tidy
    when: ansible_distribution_major_version is version_compare('7', '==')
    yum: name={{ item }} state=present
    loop:
      - tidy
    tags: packages

  - name: Copy firewalld public zone file to /etc/firewalld/zones/public.xml
    when: ansible_distribution_major_version is version_compare('7', '==')
    template: src=public.xml.j2 dest=/etc/firewalld/zones/public.xml owner=root mode=0600

  - name: Format public.xml firewalld zone file
    when: ansible_distribution_major_version is version_compare('7', '==')
    command: tidy -xml -iq -m -w 0 /etc/firewalld/zones/public.xml
    notify:
      - restart firewalld
  tags: firewall

# vim: set sw=2 ts=2:
