---
- name: Install iptables-persistent
  apt: name=iptables-persistent state=present update_cache=yes cache_valid_time=3600

- name: Copy /etc/iptables/rules.v4
  template: src=iptables.j2 dest=/etc/iptables/rules.v4 owner=root group=root mode=0600
  notify:
    - restart iptables-persistent

- name: Copy /etc/iptables/rules.v6
  template: src=ip6tables.j2 dest=/etc/iptables/rules.v6 owner=root group=root mode=0600
  notify:
    - restart iptables-persistent

# vim: set sw=2 ts=2:
