---
- name: Import OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "vars/{{ ansible_os_family }}.yml"
    - "private/vars/{{ ansible_os_family }}.yml"
  tags: always

- name: Get systemd version
  ansible.builtin.command: # noqa command-instead-of-module
    cmd: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  when: ansible_service_mgr == 'systemd'
  tags: always

- name: Set systemd version fact
  ansible.builtin.set_fact:
    __systemd_version_int: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"
  when: __systemd_version.skipped is not defined
  tags: always

- name: Include tasks to update /etc/hosts
  ansible.builtin.import_tasks: hosts.yml
  tags: hosts

- name: Install common packages
  ansible.builtin.import_tasks: packages.yml
  tags: packages

- name: Create ILRI scripts directory
  ansible.builtin.file:
    path: opt/ilri/scripts
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: scripts

- name: Copy ILRI scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/ilri/scripts
    owner: root
    group: root
    mode: 0755
  with_fileglob:
    - scripts/*.sh
  tags: scripts

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Configure secure shell daemon
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd

- name: Configure network time
  ansible.builtin.import_tasks: ntp.yml
  tags: ntp

# This should work on CentOS 7+ and Ubuntu 16.04+. As of CentOS Stream 8 the
# persistent journal is still not enabled by default. Ubuntu 22.04 seems to
# have persistent journal enabled by default.
- name: Configure persistent systemd journal
  block:
    - name: Create systemd-journald drop-in config directory
      ansible.builtin.file:
        path: /etc/systemd/journald.conf.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Enable persistent systemd journal
      ansible.builtin.copy:
        src: 00-persistent-journal.conf
        dest: /etc/systemd/journald.conf.d/00-persistent-journal.conf
        owner: root
        group: root
        mode: 0644
  when:
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '<=')) or
    (ansible_distribution == 'CentOS' and ansible_distribution_version is version('7', '==')) or
    (ansible_distribution == 'CentOS' and ansible_distribution_version is version('8', '=='))
  tags: systemd-journald

- name: Reconfigure /etc/sysctl.conf on Ubuntu
  when: ansible_distribution != "CentOS"
  ansible.builtin.template:
    src: "sysctl_{{ ansible_distribution }}.j2"
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload sysctl
  tags: sysctl

- name: Reconfigure /etc/sysctl.conf on CentOS
  when: ansible_distribution == "CentOS"
  ansible.builtin.template:
    src: "sysctl_CentOS-{{ ansible_distribution_major_version }}.j2"
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload sysctl
  tags: sysctl

- name: Set I/O scheduler
  ansible.builtin.template:
    src: etc/udev/rules.d/60-scheduler.rules.j2
    dest: /etc/udev/rules.d/60-scheduler.rules
    owner: root
    group: root
    mode: 0644
  tags: udev

- name: Configure tuned
  ansible.builtin.include_tasks: tuned.yml
  when: ansible_distribution == 'CentOS'
  tags: tuned

- name: Copy admin SSH keys
  ansible.builtin.include_tasks: ssh-keys.yml
  when: provisioning_user is defined
  tags: ssh-keys

- name: Configure sudoers
  ansible.builtin.import_tasks: sudoersd.yml
  tags: sudoers

- name: Configure RAID monitoring
  ansible.builtin.include_tasks:
    file: raid-monitoring.yml
    apply:
      tags:
        - raid-monitoring
  when: hw_raid_vendor is defined
  tags: raid-monitoring

- name: Configure backup scripts
  ansible.builtin.import_tasks: backups.yml
  tags: backups

# vim: set sw=2 ts=2:
