---
- name: Import OS-specific variables
  include_vars: "{{ item }}"
  with_items:
    - "vars/{{ ansible_os_family }}.yml"
    - "private/vars/{{ ansible_os_family }}.yml"
  tags: always

# storage and compute nodes need to know each other's IP addresses and hostnames
# for yum mirrors, SLURM, LDAP, etc, so just do that first.
- name: Add compute and storage nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_host }}.*{{ item }}.*{{ item }}\.ilri\.cgiar\.org$'
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{item}}.ilri.cgiar.org"
    state: present
  with_items: "{{ groups['compute'] | union(groups['storage']) }}"
  when: inventory_hostname != 'hpc' and ('compute' in group_names or 'storage' in group_names)
  tags: hosts

- name: Install common packages
  import_tasks: packages.yml
  tags: packages

- name: Configure firewall
  import_tasks: firewall.yml
  tags: firewall

- name: Configure secure shell daemon
  import_tasks: sshd.yml
  tags: sshd

- name: Configure network time
  import_tasks: ntp.yml
  tags: ntp

- name: Reconfigure /etc/sysctl.conf on Debian and Ubuntu
  when: ansible_distribution != "CentOS"
  template: src=sysctl_{{ ansible_distribution }}.j2 dest=/etc/sysctl.conf owner=root group=root mode=0644
  notify:
    - reload sysctl
  tags: sysctl

- name: Reconfigure /etc/sysctl.conf on CentOS
  when: ansible_distribution == "CentOS"
  template: src=sysctl_CentOS-{{ ansible_distribution_major_version }}.j2 dest=/etc/sysctl.conf owner=root group=root mode=0644
  notify:
    - reload sysctl
  tags: sysctl

- name: Reconfigure /etc/rc.local
  when: ansible_distribution == 'CentOS'
  template: src=rc.local_CentOS.j2 dest=/etc/rc.d/rc.local owner=root group=root mode=0755
  tags: rclocal

- name: Reconfigure /etc/rc.local
  when: ansible_os_family == 'Debian'
  template: src=rc.local_{{ ansible_distribution }}.j2 dest=/etc/rc.local owner=root group=root mode=0755
  tags: rclocal

- name: Set I/O scheduler
  template: src=etc/udev/rules.d/60-scheduler.rules.j2 dest=/etc/udev/rules.d/60-scheduler.rules owner=root group=root mode=0644
  tags: udev

# should really be part of compute/storage roles... but not sure the best way right now
- name: Copy IRQ affinity script
  when: ansible_distribution == 'CentOS'
  copy: src=set_irq_affinity.sh dest=/usr/local/bin/set_irq_affinity.sh owner=root mode=0755

- name: Configure tuned
  import_tasks: tuned.yml
  when: "'compute' in group_names or 'storage' in group_names"
  tags: tuned

- name: Copy admin SSH keys
  import_tasks: ssh-keys.yml
  when: provisioning_user is defined
  tags: ssh-keys

- name: Configure sudoers
  import_tasks: sudoersd.yml
  tags: sudoers

# All scripts—backups & raid mon—will be copied to /opt/ilri/scripts
- name: Create scripts directory
  file: path={{ item }} owner=root group=root mode=0755 state=directory
  with_items:
    - /opt/ilri/scripts
  tags:
    - raid-monitoring
    - backups

- name: Configure RAID monitoring
  import_tasks: raid-monitoring.yml
  when: hw_raid_vendor is defined
  tags: raid-monitoring

- name: Configure backup scripts
  import_tasks: backups.yml
  tags: backups

# vim: set sw=2 ts=2:
