---
# Hosts running Ubuntu 16.04 or CentOS 7 use the systemd init system and should
# use the built-in systemd-timesync service instead of a standalone NTP client,
# while earlier versions of those distributions should use the ntp/ntpd package.
#
# Sadly, CentOS 7 ships with systemd 219 and for some reason systemd-timesyncd
# is not bundled there (either by upstream or Redhat, I'm not sure).
#
# See: https://www.centos.org/forums/viewtopic.php?t=54021

- name: Set timezone
  when: timezone is defined and ansible_service_mgr == 'systemd'
  command: /usr/bin/timedatectl set-timezone {{ timezone }}
  tags: timezone

- name: Enable systemd's NTP client
  when: ansible_service_mgr == 'systemd' and ansible_distribution != 'CentOS'
  service: name=systemd-timesyncd enabled=yes

- name: Uninstall ntp on modern Ubuntu/Debian
  apt: name=ntp state=absent update_cache=yes
  when: ansible_os_family == 'Debian' and ansible_service_mgr == 'systemd'
  tags: packages

- name: Install ntp on old Ubuntu/Debian
  apt: name=ntp state=present update_cache=yes
  when: ansible_os_family == 'Debian' and ansible_service_mgr != 'systemd'
  tags: packages

- name: Install ntp on old CentOS
  yum: name=ntp state=present update_cache=yes
  when: ansible_distribution == 'CentOS'
  tags: packages

# vim: set ts=2 sw=2:
