---

- block:
  # Add the CentOS package signing key just in case, as it seems to be missing on
  # some installs (like from ISO).
  - name: Add CentOS package signing key
    rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
    when: ansible_distribution_major_version is version('7','==')

  - name: Configure ILRI CentOS mirror
    copy: src=CentOS-Base-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Configure ILRI CentOS mirror
    copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }} owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version('8','==') and ('compute' in group_names or 'storage' in group_names))
    with_fileglob:
      - CentOS-*-8.repo

    # 2019-05-22: disable fastestmirror plugin because it causes a delay of
    # several minutes for every yum invocation. Let's limit to storage and
    # compute hosts for now. Only seems to exist on CentOS 7.
  - name: Disable yum fastestmirror plugin
    lineinfile:
      dest: /etc/yum/pluginconf.d/fastestmirror.conf
      regexp: '^enabled=1$'
      line: "enabled=0"
      state: present
    when: (ansible_distribution_major_version is version('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Install EPEL
    yum: name=epel-release state=present

  - name: Configure ILRI EPEL mirror
    copy: src=epel-{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version('7','>=') and ('compute' in group_names or 'storage' in group_names))

  - name: Add EPEL RPM package signing key
    rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

  - name: Configure repository of ILRI CentOS packages
    copy: src=ilri.repo dest=/etc/yum.repos.d/ilri.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Set CentOS base packages
    set_fact:
      centos_base_packages:
      - git
      - acpid
      - lsof
      - sysstat
      - tmux
      - vim-enhanced

  - name: Install base packages
    yum: name={{ centos_base_packages }} state=present

# see: https://www.mellanox.com/support/mlnx-ofed-public-repository
  - name: Add Mellanox package signing key
    rpm_key:
      key: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
      state: present
    when: (ansible_distribution == 'CentOS' and ('compute' in group_names or 'storage' in group_names))

  - name: Configure Mellanox yum repository (CentOS 7)
    yum_repository:
      name: mellanox_mlnx_en
      description: Mellanox Ethernet drivers
      baseurl: https://linux.mellanox.com/public/repo/mlnx_en/5.1-1.0.4.0/rhel7.9/x86_64
      gpgkey: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
      gpgcheck: yes
    when: (ansible_distribution_major_version is version('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Configure Mellanox yum repository (CentOS 8)
    yum_repository:
      name: mellanox_mlnx_en
      description: Mellanox Ethernet drivers
      baseurl: https://linux.mellanox.com/public/repo/mlnx_en/5.1-1.0.4.0/rhel8.2/x86_64
      gpgkey: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
      gpgcheck: yes
    when: (ansible_distribution_major_version is version('8','==') and ('compute' in group_names or 'storage' in group_names))

# Install an updated Mellanox Ethernet driver (newer than the upstream kernel
# driver in CentOS 7) as well as some utilities like set_irq_affinity.sh. We
# use that script to tune the 25GbE network cards on compute and storage hosts.
# Ideally this would go in the compute or storage role, but I can't think of
# how to do that right now. The script is called by /etc/rc.local on CentOS 7.
  - name: Install Mellanox tools
    yum: name=mlnx-en-eth-only state=present
    when: (ansible_distribution == 'CentOS' and ('compute' in group_names or 'storage' in group_names))
  tags: packages

- name: Disable annoying cockpit notice in MOTD
  file: path=/etc/motd.d/cockpit state=absent
  when: ansible_distribution_major_version is version('8','==')

# vim: set ts=2 sw=2:
