---
# Add the CentOS package signing key just in case, as it seems to be missing on
# some installs (like from ISO).
- name: Add CentOS package signing key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}

# HPC has an EPEL mirror and we should probably manage the epel.repo file to
# point to it, but I want to work on other things right now (like the major
# updating and testing of these playbooks for CentOS 7).
- name: Install EPEL
  yum: name=epel-release state=present

- name: Add EPEL RPM package signing key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Configure repository of ILRI CentOS packages
  copy: src=ilri.repo dest=/etc/yum.repos.d/ilri.repo owner=root group=root mode=0644

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - git
    - acpid
    - lsof
    - sysstat
    - tmux
    - vim

# vim: set ts=2 sw=2:
