---
# 2024-02-19: none of our servers support this yet so we can remove it globally
- name: Uninstall fwupd
  ansible.builtin.package:
    name: fwupd
    state: absent
  tags: packages

- name: Install common packages on CentOS
  ansible.builtin.include_tasks: packages_CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags: packages

- name: Install common packages on Ubuntu
  ansible.builtin.include_tasks: packages_Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: packages

- name: Install common packages on Debian
  ansible.builtin.include_tasks: packages_Debian.yml
  when: ansible_distribution == 'Debian'
  tags: packages

# vim: set ts=2 sw=2:
