---

- block:
  # Add the CentOS package signing key just in case, as it seems to be missing on
  # some installs (like from ISO).
  - name: Add CentOS package signing key
    rpm_key:
      state: present
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
    when: ansible_distribution_major_version is version('7','==')

  - name: Configure ILRI CentOS mirror
    copy:
      src: CentOS-Base-7.repo
      dest: /etc/yum.repos.d/CentOS-Base.repo
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version is version('7','==')
      - ('compute' in group_names or 'storage' in group_names)

  - name: Configure ILRI CentOS Stream mirror
    copy:
      src: "{{ item }}"
      dest: /etc/yum.repos.d/{{ item | basename }}
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_release == 'Stream'
    with_fileglob:
      - CentOS-Stream-*.repo

    # 2019-05-22: disable fastestmirror plugin because it causes a delay of
    # several minutes for every yum invocation. Let's limit to storage and
    # compute hosts for now. Only seems to exist on CentOS 7.
  - name: Disable yum fastestmirror plugin
    lineinfile:
      dest: /etc/yum/pluginconf.d/fastestmirror.conf
      regexp: '^enabled=1$'
      line: "enabled=0"
      state: present
    when:
      - ansible_distribution_major_version is version('7','==')
      - ('compute' in group_names or 'storage' in group_names)

  - name: Install EPEL
    ansible.builtin.package:
      name: epel-release
      state: present
    when: ansible_distribution_major_version is version('7','==')

# Fedora docs recommends enabling EPEL and EPEL Next on CentOS Stream
# See: https://docs.fedoraproject.org/en-US/epel/#_el8
  - name: Install EPEL
    ansible.builtin.package:
      name: ['epel-release', 'epel-next-release']
      state: present
    when: ansible_distribution_release == 'Stream'

  - name: Configure ILRI EPEL mirror
    copy:
      src: epel-{{ ansible_distribution_major_version }}.repo
      dest: /etc/yum.repos.d/epel.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_major_version is version('7','>=')

  - name: Configure ILRI EPEL Next mirror
    copy:
      src: epel-8-next.repo
      dest: /etc/yum.repos.d/epel-next.repo
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution_release == 'Stream'

  - name: Add EPEL RPM package signing key
    rpm_key:
      state: present
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

  - name: Configure repository of ILRI CentOS packages
    copy:
      src: ilri.repo
      dest: /etc/yum.repos.d/ilri.repo
      owner: root
      group: root
      mode: 0644
    when:
      - ansible_distribution_major_version is version('7','==')
      - ('compute' in group_names or 'storage' in group_names)

  - name: Set CentOS base packages
    set_fact:
      centos_base_packages:
      - git
      - acpid
      - lsof
      - sysstat
      - tmux
      - vim-enhanced
      - unzip
      - pciutils

  - name: Install base packages
    ansible.builtin.package:
      name: "{{ centos_base_packages }}"
      state: present
  tags: packages

- name: Disable annoying cockpit notice in MOTD
  file:
    path: /etc/motd.d/cockpit
    state: absent
  when: ansible_distribution_major_version is version('8','==')

# vim: set ts=2 sw=2:
