---

- block:
  - name: Configure apt mirror
    template: src=sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

  - name: Set Debian base packages
    set_fact:
      debian_base_packages:
      - git
      - tmux
      - iotop
      - htop
      - strace
      - s3cmd
      - cron-apt
      - safe-rm
      - debian-goodies
      - lzop
      - vim
      - acpid
      - schedtool
      - debconf
      - debconf-utils
      - sysstat
      - software-properties-common

  - name: Install base packages
    apt: name={{ debian_base_packages }} state=present update_cache=yes cache_valid_time=3600

  - name: Configure cron-apt
    import_tasks: cron-apt.yml
    tags: cron-apt
  tags: packages

# vim: set ts=2 sw=2:
