---

- block:
  - name: Configure apt mirror
    ansible.builtin.template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644
    register: configure_apt_mirror

  - name: Update apt cache
    ansible.builtin.package:
      update_cache: true
    when:
      configure_apt_mirror is changed

  - name: Install base packages
    ansible.builtin.package:
      name:
        - git
        - tmux
        - iotop
        - htop
        - strace
        - s3cmd
        - cron-apt
        - safe-rm
        - debian-goodies
        - lzop
        - vim
        - acpid
        - debconf
        - debconf-utils
        - sysstat
        - software-properties-common
      state: present
      cache_valid_time: 3600

  - name: Configure cron-apt
    ansible.builtin.import_tasks: cron-apt.yml
    tags: cron-apt
  tags: packages

# vim: set ts=2 sw=2:
