---

- name: Configure CentOS packages
  block:
    - name: Configure ILRI CentOS Stream mirror
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/yum.repos.d/{{ item | basename }}
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution_release == 'Stream'
      with_fileglob:
        - CentOS-Stream-*.repo

#   Fedora docs recommends enabling EPEL and EPEL Next on CentOS Stream
#   See: https://docs.fedoraproject.org/en-US/epel/#_el8
    - name: Install EPEL
      ansible.builtin.package:
        name: ['epel-release', 'epel-next-release']
        state: present
      when: ansible_distribution_release == 'Stream'

    - name: Configure ILRI EPEL Next mirror
      ansible.builtin.copy:
        src: epel-8-next.repo
        dest: /etc/yum.repos.d/epel-next.repo
        owner: root
        group: root
        mode: 0644
      when: ansible_distribution_release == 'Stream'

    - name: Add EPEL RPM package signing key
      ansible.builtin.rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: Configure repository of ILRI CentOS packages
      ansible.builtin.copy:
        src: ilri.repo
        dest: /etc/yum.repos.d/ilri.repo
        owner: root
        group: root
        mode: 0644
      when: "'compute' in group_names or 'storage' in group_names"

    - name: Install base packages
      ansible.builtin.package:
        name:
          - git
          - acpid
          - lsof
          - sysstat
          - tmux
          - vim-enhanced
          - unzip
          - pciutils
          - zstd
          - bzip2
          - mosh
        state: present
  tags: packages

- name: Disable annoying cockpit notice in MOTD
  ansible.builtin.file:
    path: /etc/motd.d/cockpit
    state: absent
  when: ansible_distribution_major_version is version('8', '==')

# vim: set ts=2 sw=2:
