---
- name: Configure CentOS packages
  tags: packages
  block:
    - name: Configure CentOS Stream mirrors (CentOS Stream 9)
      ansible.builtin.copy:
        src: etc/yum.repos.d/centos.repo
        dest: /etc/yum.repos.d/centos.repo
        owner: root
        group: root
        mode: "0644"
      when:
        - ansible_distribution_release == 'Stream'
        - ansible_distribution_major_version is version('9', '==')

    # Fedora docs recommends enabling EPEL and EPEL Next on CentOS Stream
    # See: https://docs.fedoraproject.org/en-US/epel/getting-started/#_el9
    - name: Install EPEL
      ansible.builtin.package:
        name: [epel-release, epel-next-release]
        state: present
      when: ansible_distribution_release == 'Stream'

    - name: Configure ILRI EPEL mirrors
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/yum.repos.d/{{ item | basename }}
        owner: root
        group: root
        mode: "0644"
      when:
        - ansible_distribution_release == 'Stream'
        - ansible_distribution_major_version is version('9', '==')
        - "'addis_compute' not in group_names"
      loop:
        - etc/yum.repos.d/epel.repo
        - etc/yum.repos.d/epel-next.repo

    - name: Add EPEL RPM package signing key
      ansible.builtin.rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: Configure repository of ILRI CentOS packages
      ansible.builtin.copy:
        src: etc/yum.repos.d/ilri.repo
        dest: /etc/yum.repos.d/ilri.repo
        owner: root
        group: root
        mode: "0644"
      when: "'compute' in group_names or 'storage' in group_names"

    # Intel Math Kernel Library (for some HPC applications)
    # See: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html
    - name: Configure repository of Intel CentOS packages
      ansible.builtin.copy:
        src: etc/yum.repos.d/oneAPI.repo
        dest: /etc/yum.repos.d/oneAPI.repo
        owner: root
        group: root
        mode: "0644"
      when:
        - ansible_distribution_release == 'Stream'
        - ansible_distribution_major_version is version('9', '==')
        - "'compute' in group_names"

    - name: Install base packages
      ansible.builtin.package:
        name:
          - git
          - acpid
          - lsof
          - sysstat
          - tmux
          - pciutils
          - zstd
          - mosh
        state: present

    - name: Remove irqbalance
      when: "'compute' in group_names or 'storage' in group_names"
      ansible.builtin.package:
        name: irqbalance
        state: absent

- name: Disable annoying cockpit notice in MOTD
  ansible.builtin.file:
    path: /etc/motd.d/cockpit
    state: absent
  when: ansible_distribution_major_version is version('8', '>=')

# vim: set ts=2 sw=2:
