---

- block:
  # Add the CentOS package signing key just in case, as it seems to be missing on
  # some installs (like from ISO).
  - name: Add CentOS package signing key
    rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}

  - name: Configure ILRI CentOS mirror
    copy: src=CentOS-Base-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version_compare('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Install EPEL
    yum: name=epel-release state=present

  - name: Configure ILRI EPEL mirror
    copy: src=epel-7.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version_compare('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Add EPEL RPM package signing key
    rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

  - name: Configure repository of ILRI CentOS packages
    copy: src=ilri.repo dest=/etc/yum.repos.d/ilri.repo owner=root group=root mode=0644
    when: (ansible_distribution_major_version is version_compare('7','==') and ('compute' in group_names or 'storage' in group_names))

  - name: Set CentOS base packages
    set_fact:
      centos_base_packages:
      - git
      - acpid
      - lsof
      - sysstat
      - tmux
      - vim

  - name: Install base packages
    yum: name={{ centos_base_packages }} state=present
  tags: packages

# vim: set ts=2 sw=2:
