---
# MegaCLI binaries are statically compiled, so just use the same repo for all
# Debian-family hosts
- name: Add Debian-family HWRaid repo
  ansible.builtin.apt_repository:
    repo: 'deb http://hwraid.le-vert.net/debian wheezy main'
    state: present
  when:
    - ansible_os_family == 'Debian'
    - "'lsi' in hw_raid_vendor"

- name: Import HWRaid repo's signing key
  ansible.builtin.apt_key:
    url: https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key
    state: present
  when:
    - ansible_os_family == 'Debian'
    - "'lsi' in hw_raid_vendor"

- name: Install LSI MegaCLI tools
  ansible.builtin.package:
    name: megacli
    state: present
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
    - "'lsi' in hw_raid_vendor"

- name: Remove old Debian-based HPE MCP repos
  ansible.builtin.apt_repository:
    repo: 'deb {{ item }} {{ ansible_distribution_release }}/current non-free'
    state: absent
  loop:
    - http://downloads.linux.hpe.com/SDR/repo/mcp
    - https://downloads.linux.hpe.com/SDR/repo/mcp
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

# Add HPC IP to nodes that are using its mirrors for HW RAID utilities
- name: Add HPC to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars["hpc"].ansible_host }}.*hpc.*hpc\.ilri\.cgiar\.org$'
    line: "{{ hostvars['hpc'].ansible_host }} hpc hpc.ilri.cgiar.org"
    state: present
  when: hw_raid_vendor is defined

- name: Add ILRI mirror of Debian-based HPE MCP repository
  ansible.builtin.template:
    src: hpc_ilri_cgiar_org_mirror_mcp.list.j2
    dest: /etc/apt/sources.list.d/hpc_ilri_cgiar_org_mirror_mcp.list
    mode: 0644
    owner: root
    group: root
  register: add_hpe_mcp_apt_repository
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Remove HPE-MCP key from apt-key
  ansible.builtin.apt_key:
    id: 57446EFDE098E5C934B69C7DC208ADDE26C2B797
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Check HPE MCP package signing key
  ansible.builtin.stat:
    path: /usr/share/keyrings/hpePublicKey2048_key1.pub
  register: hpe_mcp_signing_key_stat
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Download HPE MCP package signing key
  ansible.builtin.get_url:
    url: https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub
    dest: /usr/share/keyrings/hpePublicKey2048_key1.pub
    owner: root
    group: root
    mode: 0644
  register: download_hpe_mcp_signing_key
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"
    - not hpe_mcp_signing_key_stat.stat.exists

- name: Update apt cache
  ansible.builtin.apt: # noqa no-handler
    update_cache: true
  when:
    - (download_hpe_mcp_signing_key.status_code is defined and download_hpe_mcp_signing_key.status_code == 200) or add_hpe_mcp_apt_repository is changed
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Install HPE Smart Storage Administrator CLI
  ansible.builtin.package:
    name: ssacli
    state: present
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

# In ILRI CentOS repo, from:
# http://sarepos.cpanel.net/centos
- name: Install LSI MegaCLI tools
  ansible.builtin.package:
    name: MegaCli
    state: present
  when:
    - ansible_distribution == 'CentOS'
    - "'lsi' in hw_raid_vendor"

- name: Configure ILRI mirror of HPE MCP repository
  ansible.builtin.template:
    src: hpe-mcp.repo.j2
    dest: /etc/yum.repos.d/hpe-mcp.repo
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == 'CentOS'
    - "'hp' in hw_raid_vendor"

- name: Install HPE Smart Storage Administrator CLI
  ansible.builtin.package:
    name: ssacli
    state: present
  when:
    - ansible_distribution == 'CentOS'
    - "'hp' in hw_raid_vendor"

# HPE Array tools were replaced by the Smart Storate Administrator CLI
- name: Remove HPE Array tools
  ansible.builtin.package:
    name: hpacucli
    state: absent
  when:
    - ansible_distribution == 'CentOS'
    - "'hp' in hw_raid_vendor"

# HPE Array tools were replaced by the Smart Storate Administrator CLI
- name: Remove HPE Array tools
  ansible.builtin.package:
    name: hpssacli
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Install mailx
  ansible.builtin.package:
    name: mailx
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install s-nail
  ansible.builtin.package: name=s-nail state=present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('18.04', '>=')

- name: Copy LSI RAID monitoring script
  ansible.builtin.template:
    src: scripts/lsi-raid-monitoring.sh.j2
    dest: /opt/ilri/scripts/lsi-raid-monitoring.sh
    owner: root
    group: root
    mode: 0750
  when: "'lsi' in hw_raid_vendor"

- name: Copy HPE RAID monitoring script
  ansible.builtin.template:
    src: scripts/hp-raid-monitoring.sh.j2
    dest: /opt/ilri/scripts/hp-raid-monitoring.sh
    owner: root
    group: root
    mode: 0750
  when: "'hp' in hw_raid_vendor"

- name: Configure RAID monitoring cron job
  ansible.builtin.template:
    src: cron/raid-monitoring.j2
    dest: /etc/cron.d/1raid-monitoring
    owner: root
    group: root
    mode: 0644

# vim: set sw=2 ts=2:
