---
# Add HPC IP to nodes that are using its mirrors for HW RAID utilities
- name: Add HPC to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '{{ hostvars["hpc"].ansible_host }}.*hpc.*hpc\.ilri\.cgiar\.org$'
    line: "{{ hostvars['hpc'].ansible_host }} hpc hpc.ilri.cgiar.org"
    state: present
  when: "'hp' in hw_raid_vendor or 'lsi' in hw_raid_vendor"

# 2024-12-24: As of this writing, no repositories use this key.
- name: Remove old HPE MCP repository signing key
  ansible.builtin.file:
    path: /usr/share/keyrings/hpePublicKey2048_key1.pub
    state: absent
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

# 2024-12-24: As of this writing all HPE MCP repositories use this key. Here we
# check for the binary version of the key because it seems to work better than
# the ASCII-armored versions on Ubuntu 22.04.
- name: Check HPE MCP package signing key
  ansible.builtin.stat:
    path: /etc/apt/keyrings/hpePublicKey2048_key2.pub.gpg
  register: hpe_mcp_binary_signing_key
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Download ASCII-armored HPE MCP package signing key
  ansible.builtin.get_url:
    url: https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key2.pub
    dest: /etc/apt/keyrings/hpePublicKey2048_key2.pub
    owner: root
    group: root
    mode: "0644"
  register: download_armored_hpe_mcp_signing_key
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"
    - not hpe_mcp_binary_signing_key.stat.exists

- name: De-armor HPE MCP package signing key
  ansible.builtin.shell: "gpg --dearmor < /etc/apt/keyrings/hpePublicKey2048_key2.pub > /etc/apt/keyrings/hpePublicKey2048_key2.pub.gpg"
  args:
    creates: /etc/apt/keyrings/hpePublicKey2048_key2.pub.gpg
  register: hpe_mcp_dearmored_signing_key
  when: download_armored_hpe_mcp_signing_key is changed

- name: Add Debian-based HPE MCP repository
  ansible.builtin.deb822_repository:
    name: hpe-mcp
    types: deb
    uris: https://hpc.ilri.cgiar.org/mirror/mcp
    suites: '{{ ansible_distribution_release }}/current'
    components: non-free
    architectures: amd64
    signed_by: /etc/apt/keyrings/hpePublicKey2048_key2.pub.gpg
    state: present
  register: add_hpe_mcp_apt_repository
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Update apt cache
  ansible.builtin.apt: # noqa no-handler
    update_cache: true
  when:
    - (hpe_mcp_dearmored_signing_key is changed or add_hpe_mcp_apt_repository is changed)
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

- name: Install HPE Smart Storage Administrator CLI
  ansible.builtin.package:
    name: ssacli
    state: present
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
    - "'hp' in hw_raid_vendor"

# In ILRI CentOS repo, from:
# http://sarepos.cpanel.net/centos
- name: Install LSI MegaCLI tools
  ansible.builtin.package:
    name: MegaCli
    state: present
  when:
    - ansible_distribution == 'CentOS'
    - "'lsi' in hw_raid_vendor"

- name: Configure ILRI mirror of HPE MCP repository
  ansible.builtin.template:
    src: hpe-mcp.repo.j2
    dest: /etc/yum.repos.d/hpe-mcp.repo
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version is version('8', '==')
    - "'hp' in hw_raid_vendor"

- name: Configure HPE SPP repository
  ansible.builtin.template:
    src: hpe-spp.repo.j2
    dest: /etc/yum.repos.d/hpe-spp.repo
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version is version('9', '==')
    - "'hp' in hw_raid_vendor"

- name: Install HPE Smart Storage Administrator CLI
  ansible.builtin.package:
    name: ssacli
    state: present
  when:
    - ansible_distribution == 'CentOS'
    - "'hp' in hw_raid_vendor"

- name: Copy LSI RAID monitoring script
  ansible.builtin.template:
    src: scripts/lsi-raid-monitoring.sh.j2
    dest: /opt/ilri/scripts/lsi-raid-monitoring.sh
    owner: root
    group: root
    mode: "0750"
  when: "'lsi' in hw_raid_vendor"

- name: Copy HPE RAID monitoring script
  ansible.builtin.template:
    src: scripts/hp-raid-monitoring.sh.j2
    dest: /opt/ilri/scripts/hp-raid-monitoring.sh
    owner: root
    group: root
    mode: "0750"
  when: "'hp' in hw_raid_vendor"

- name: Configure RAID monitoring cron job
  ansible.builtin.template:
    src: cron/raid-monitoring.j2
    dest: /etc/cron.d/1raid-monitoring
    owner: root
    group: root
    mode: "0644"
  when: "'hp' in hw_raid_vendor or 'lsi' in hw_raid_vendor"

# TODO: according to mdadm.conf we can only use ONE email address
- name: Configure MAILADDR for mdadm
  ansible.builtin.lineinfile:
    path: /etc/mdadm/mdadm.conf
    regexp: ^MAILADDR\s+{{ sysadmin_emails[0] }}$
    line: MAILADDR {{ sysadmin_emails[0] }}
    state: present
  when: "'md' in hw_raid_vendor"

# vim: set sw=2 ts=2:
