---
- name: Create ILRI scripts directory
  ansible.builtin.file:
    path: /opt/ilri/scripts
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Copy ILRI scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/ilri/scripts
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - scripts/*.sh

- name: Remove mailx
  ansible.builtin.package:
    name: mailx
    state: absent
  when: ansible_distribution == 'CentOS'

- name: Install s-nail
  ansible.builtin.package:
    name: s-nail
    state: present
  when:
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('18.04', '>=')) or
    (ansible_distribution == 'Debian' and ansible_distribution_version is version('11', '>=')) or
    ansible_distribution == 'CentOS'

# unattended-upgrades expects /usr/bin/mail. Only tested on Ubuntu for now. Also
# note that unattended-upgrades will try sendmail (postfix) first, which will
# mail as "root@hostname" and probably not get delivered. Even so, with s-nail,
# we can only deliver mail if we have been added to the whitelist by CGNET...
# So basically we just trust that security updates work and get mails on fail
# *sometimes*, on *some* hosts.
#
# See: https://unix.stackexchange.com/questions/699230/how-to-use-s-nail-with-unattended-upgrades
# See: https://patineboot.com/article/buildiing-home-server-with-ubuntu/
- name: Use s-nail as mail
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.04', '>=')
  community.general.alternatives:
    name: mail
    link: /usr/bin/mail
    path: /usr/bin/s-nail
    priority: 10

# Prefer the system s-nail configuration over this
- name: Remove /root/.mailrc
  ansible.builtin.file:
    path: /root/.mailrc
    state: absent

- name: Configure /etc/s-nail.rc
  ansible.builtin.template:
    src: mailrc.j2
    dest: /etc/s-nail.rc
    owner: root
    group: root
    mode: "0644"

# vim: set sw=2 ts=2:
