---
- name: Create ILRI scripts directory
  ansible.builtin.file:
    path: /opt/ilri/scripts
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Copy ILRI scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/ilri/scripts
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - scripts/*.sh

- name: Remove mailx
  ansible.builtin.package:
    name: mailx
    state: absent
  when: ansible_distribution == 'CentOS'

- name: Install s-nail
  ansible.builtin.package:
    name: s-nail
    state: present
  when:
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('18.04', '>=')) or
    (ansible_distribution == 'Debian' and ansible_distribution_version is version('11', '>=')) or
    ansible_distribution == 'CentOS'

# Prefer the system s-nail configuration over this
- name: Remove /root/.mailrc
  ansible.builtin.file:
    path: /root/.mailrc
    state: absent

- name: Configure /etc/s-nail.rc
  ansible.builtin.template:
    src: mailrc.j2
    dest: /etc/s-nail.rc
    owner: root
    group: root
    mode: "0644"

# vim: set sw=2 ts=2:
