---
# Manage these exclusively
- name: Configure public keys for provisioning user
  ansible.posix.authorized_key:
    user: "{{ provisioning_user.name }}"
    key: "{{ lookup('file', 'private/data/common/ssh-keys/{{ provisioning_user.name }}') }}"
    exclusive: true
  tags: ssh-keys

# Do not manage these exclusively
- name: Configure public keys for SSH users
  when:
    - ssh_allowed_users is defined
    - "'root' not in ssh_allowed_users"
    - ssh_password_authentication == 'disabled'
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'private/data/common/ssh-keys/{{ item }}') }}"
  with_items:
    - "{{ ssh_allowed_users }}"
  tags: ssh-keys

# vim: set sw=2 ts=2:
