---
- name: Configure sshguard
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    mode: "0644"
  loop:
    - { src: etc/sshguard.conf.j2, dest: /etc/sshguard.conf }
    - { src: etc/sshguard.whitelist.j2, dest: /etc/sshguard.whitelist }
  notify: restart sshguard

- name: Create sshguard service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/sshguard.service.d
    state: directory
    owner: root
    mode: "0755"

- name: Configure sshguard service override
  ansible.builtin.template:
    src: etc/systemd/system/sshguard.service.d/override.conf.j2
    dest: /etc/systemd/system/sshguard.service.d/override.conf
    owner: root
    mode: "0644"
  notify:
    - reload systemd
    - restart sshguard

- name: Start and enable sshguard service
  ansible.builtin.systemd_service:
    name: sshguard.service
    state: started
    enabled: true

# vim: set sw=2 ts=2:
