---
- name: Add provisioning user to sudoers
  ansible.builtin.template:
    src: provisioning.j2
    dest: /etc/sudoers.d/provisioning
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  when: ansible_os_family == "Debian"

- name: Add provisioning user to sudoers
  ansible.builtin.template:
    src: provisioning.j2
    dest: /etc/sudoers.d/provisioning
    owner: root
    group: root
    mode: "0600"
    validate: visudo -cf %s
  when: ansible_os_family != "Debian"

- name: Configure extra sudo users
  ansible.builtin.template:
    src: extra_sudoers.j2
    dest: /etc/sudoers.d/extra_sudoers
    owner: root
    group: root
    mode: "0440"
    validate: visudo -cf %s
  when: ansible_os_family == "Debian"

- name: Configure extra sudo users
  ansible.builtin.template:
    src: extra_sudoers.j2
    dest: /etc/sudoers.d/extra_sudoers
    owner: root
    group: root
    mode: "0600"
    validate: visudo -cf %s
  when: ansible_os_family != "Debian"

# cloud-init adds sudo users for us, but for now I would prefer to remove that
# so we can have a consistent sudo on all our hosts (some of which do not use
# cloud-init). We have to do this at the end so we don't lose sudo access in
# the middle of our playbook.
- name: Remove cloud-init sudoers
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent

# vim: set ts=2 sw=2:
