---
- name: Install tuned on CentOS 7+ hosts
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version is version('7', '>=')
  ansible.builtin.package:
    name: tuned
    state: installed
  tags: tuned

- name: Start and enable tuned service on CentOS 7+ hosts
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version is version('7', '>=')
  ansible.builtin.systemd:
    name: tuned
    state: started
    enabled: yes
  tags: tuned

- name: Set default tuned profile
  when: tuned_profile is defined
  ansible.builtin.command: tuned-adm profile {{ tuned_profile }}
  tags: tuned

# vim: set sw=2 ts=2:
