---

- name: Install unattended-upgrades
  apt: name=unattended-upgrades state=present update_cache=yes

- name: Configure unattended-upgrades
  template: src={{ item.src }} dest={{ item.dest }} mode=0644 owner=root group=root
  with_items:
    - { src: 'apt.conf.d/02periodic.j2', dest: '/etc/apt/apt.conf.d/02periodic' }
    - { src: 'apt.conf.d/20auto-upgrades.j2', dest: '/etc/apt/apt.conf.d/20auto-upgrades' }
    - { src: 'apt.conf.d/50unattended-upgrades.j2', dest: '/etc/apt/apt.conf.d/50unattended-upgrades' }

# vim: set sw=2 ts=2:
