---
- name: Install GlusterFS and dependencies
  yum: name={{ item }} state=present
  with_items:
    - glusterfs-fuse
    - libsemanage-python

- name: Create mount points
  when: glusterfs_mounts is defined
  file: dest={{ item.mount_point }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }}
  with_items: "{{ glusterfs_mounts }}"

- name: Set SELinux boolean
  when: glusterfs_mounts is defined
  seboolean: name=use_fusefs_home_dirs state=true persistent=true

- name: Mount glusterfs volumes
  when: glusterfs_mounts is defined
  mount: name={{ item.mount_point }} src={{ item.mount_src }} fstype={{ item.mount_fs }} opts={{ item.mount_opts }} state={{ item.mount_state }}
  with_items: "{{ glusterfs_mounts }}"

# vim: set ts=2 sw=2:
