---
- name: Install GlusterFS client packages (CentOS 7)
  ansible.builtin.package:
    name:
      - glusterfs-fuse
      - libsemanage-python # required by Ansible's seboolean module
    state: present
  when: ansible_distribution_major_version is version('7','==')
  tags: glusterfs-client

- name: Install GlusterFS client packages (CentOS Stream 8)
  ansible.builtin.package:
    name:
      - glusterfs-fuse
      - python3-libsemanage.x86_64 # required by Ansible's seboolean module
    state: present
  when: ansible_distribution_major_version is version('8','==')
  tags: glusterfs-client

- name: Create mount points
  when: glusterfs_mounts is defined
  ansible.builtin.file:
    dest: "{{ item.mount_point }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  loop: "{{ glusterfs_mounts }}"
  tags: glusterfs-client

- name: Set SELinux boolean
  when: glusterfs_mounts is defined
  ansible.posix.seboolean:
    name: use_fusefs_home_dirs
    state: true
    persistent: true
  tags: glusterfs-client

- name: Mount GlusterFS volumes
  when: glusterfs_mounts is defined
  ansible.posix.mount:
    name: "{{ item.mount_point }}"
    src: "{{ item.mount_src }}"
    fstype: "{{ item.mount_fs }}"
    opts: "{{ item.mount_opts }}"
    state: "{{ item.mount_state }}"
  loop: "{{ glusterfs_mounts }}"
  tags: glusterfs-client

# vim: set ts=2 sw=2:
