---
- import_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- import_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
