---
- name: Set fact for old GlusterFS package repositories
  set_fact:
    old_glusterfs_package_repositories:
      - centos-release-gluster5
      - centos-release-gluster6
      - centos-release-gluster7

- name: Remove old GlusterFS package repositories
  yum: name={{ old_glusterfs_package_repositories }} state=absent

- name: Enable GlusterFS packages from CentOS SIG
  yum: name=centos-release-gluster8 state=present

- name: Configure Mellanox network cards
  include_tasks: mellanox.yml
  tags: mellanox

- name: Configure GlusterFS client
  include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
