---
# Temporary fix for broken CentOS Stream 8 mirrors
#
# TODO: remove when we migrate to CentOS Stream 9
- name: Override CentOS Gluster mirror
  when: ansible_distribution_major_version is version('8', '==')
  ansible.builtin.copy:
    src: CentOS-Gluster-10.repo
    dest: /etc/yum.repos.d/CentOS-Gluster-10.repo
    owner: root
    group: root
    mode: "0644"

- name: Remove old GlusterFS package repositories
  ansible.builtin.package:
    name:
      - centos-release-gluster5
      - centos-release-gluster6
      - centos-release-gluster7
      - centos-release-gluster8
      - centos-release-gluster9
    state: absent

- name: Enable GlusterFS packages from CentOS SIG
  ansible.builtin.package:
    name: centos-release-gluster10
    state: present

- name: Configure Mellanox network cards
  ansible.builtin.include_tasks: mellanox.yml
  tags: mellanox

- name: Configure GlusterFS client
  ansible.builtin.include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  ansible.builtin.include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
