---
# used for old versions of GlusterFS that were hosted on gluster.org
- name: Remove old GlusterFS yum repo
  file: path=/etc/yum.repos.d/glusterfs-epel.repo state=absent

- name: Enable GlusterFS packages from CentOS SIG
  yum: name=centos-release-gluster312 state=present

- name: Configure GlusterFS client
  import_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  import_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
