---
- name: Set fact for old GlusterFS package repositories
  set_fact:
    old_glusterfs_package_repositories:
      - centos-release-gluster5
      - centos-release-gluster6
      - centos-release-gluster7

- name: Remove old GlusterFS package repositories
  yum: name={{ old_glusterfs_package_repositories }} state=absent

- name: Enable GlusterFS packages from CentOS SIG
  yum: name=centos-release-gluster8 state=present

- name: Configure Mellanox IRQ affinity service
  template: src=set-mellanox-irq-affinity.service.j2 dest=/etc/systemd/system/set-mellanox-irq-affinity.service mode=0644 owner=root group=root
  register: mellanox_systemd_service

# need to reload to pick up service/timer/environment changes
- name: Reload systemd daemon
  systemd: daemon_reload=yes
  when: mellanox_systemd_service is changed

- name: Start and enable Mellanox IRQ affinity service
  systemd: name=set-mellanox-irq-affinity.service state=started enabled=yes

- name: Configure GlusterFS client
  include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
