---
- name: Remove old GlusterFS package repositories
  ansible.builtin.package:
    name:
      - centos-release-gluster5
      - centos-release-gluster6
      - centos-release-gluster7
      - centos-release-gluster8
      - centos-release-gluster9
    state: absent

- name: Enable GlusterFS packages from CentOS SIG
  ansible.builtin.package:
    name: centos-release-gluster10
    state: present

- name: Configure Mellanox network cards
  ansible.builtin.include_tasks: mellanox.yml
  tags: mellanox

- name: Configure GlusterFS client
  ansible.builtin.include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  ansible.builtin.include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
