---
- name: Enable GlusterFS packages from CentOS SIG
  yum: name=centos-release-gluster7 state=present

- name: Configure GlusterFS client
  include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

# vim: set sw=2 ts=2:
