---
- name: Remove old GlusterFS package repositories
  ansible.builtin.package:
    name:
      - centos-release-gluster5
      - centos-release-gluster6
      - centos-release-gluster7
      - centos-release-gluster8
      - centos-release-gluster9
      - centos-release-gluster10
    state: absent

- name: Enable GlusterFS packages from CentOS SIG
  ansible.builtin.package:
    name: centos-release-gluster11
    state: present

- name: Configure GlusterFS client
  ansible.builtin.include_tasks: client.yml
  when: glusterfs_role == 'client'
  tags: glusterfs-client

- name: Configure GlusterFS server
  ansible.builtin.include_tasks: server.yml
  when: glusterfs_role == 'server'
  tags: glusterfs-server

- name: Increase network ring buffers
  ansible.builtin.copy:
    src: etc/udev/rules.d/71-ethtool.rules
    dest: /etc/udev/rules.d/71-ethtool.rules
    mode: "0644"
    owner: root
    group: root

# vim: set sw=2 ts=2:
