---
# see: https://network.nvidia.com/support/mlnx-ofed-public-repository/
- name: Add Mellanox package signing key
  ansible.builtin.rpm_key:
    key: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    state: present
  tags: mellanox

- name: Configure Mellanox yum repository (CentOS 8)
  ansible.builtin.yum_repository:
    name: mellanox_mlnx_en
    description: Mellanox Ethernet drivers
    baseurl: https://linux.mellanox.com/public/repo/mlnx_en/5.1-1.0.4.0/rhel8.2/x86_64
    gpgkey: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    gpgcheck: true
  when: ansible_distribution_major_version is version('8', '==')
  tags: mellanox

- name: Configure Mellanox yum repository (CentOS Stream 9)
  ansible.builtin.yum_repository:
    name: mellanox_mlnx_en
    description: Mellanox Ethernet drivers
    baseurl: https://linux.mellanox.com/public/repo/mlnx_en/latest/rhel9.5/x86_64
    gpgkey: https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    gpgcheck: true
  when: ansible_distribution_major_version is version('9', '==')
  tags: mellanox

# Install an updated Mellanox Ethernet driver (newer than the upstream kernel
# driver in CentOS 7) as well as some utilities like set_irq_affinity.sh. We
# use that script to tune the 25GbE network cards on compute and storage hosts.
# Ideally this would go in the compute or storage role, but I can't think of
# how to do that right now. The script is called by /etc/rc.local on CentOS 7.
#
# Depending on how this driver behaves with future CentOS / RHEL releases I
# might switch to only using the CentOS kernel's driver and only install the
# mlnx-en-utils for the set_irq_affinity.sh script.
- name: Install Mellanox drivers/tools
  ansible.builtin.package:
    name: mlnx-en-eth-only
    state: present
  tags: mellanox

- name: Configure Mellanox IRQ affinity service
  ansible.builtin.template:
    src: set-mellanox-irq-affinity.service.j2
    dest: /etc/systemd/system/set-mellanox-irq-affinity.service
    mode: "0644"
    owner: root
    group: root
  notify: Start and enable Mellanox IRQ affinity service
  tags: mellanox

- name: Increase network ring buffers
  ansible.builtin.copy:
    src: etc/udev/rules.d/71-ethtool.rules
    dest: /etc/udev/rules.d/71-ethtool.rules
    mode: "0644"
    owner: root
    group: root
  tags: mellanox

- name: Remove deprecated Mellanox rx/tx descriptors service
  ansible.builtin.file:
    path: /etc/systemd/system/set-mellanox-descriptors.service
    state: absent
  tags: mellanox

# vim: set sw=2 ts=2:
