---
- name: Install disk utilities and glusterfs-server
  ansible.builtin.package:
    name: [gdisk, xfsprogs, nfs-utils, htop, glusterfs-server]
    state: present
  tags: glusterfs-server

- name: Start and enable glusterd service
  ansible.builtin.systemd:
    name: glusterd
    state: started
    enabled: true
  tags: glusterfs-server

# belongs in a proper "storage" role, but this will have to do for now
- name: Remove irqbalance
  ansible.builtin.package:
    name: irqbalance
    state: absent
  tags:
    - irqbalance
    - glusterfs-server

# vim: set sw=2 ts=2:
