---

- name: Install disk utilities
  yum: name={{ item }} state=installed
  with_items:
    - gdisk
    - xfsprogs

- name: Install glusterfs-server dependencies
  yum: name={{ item }} state=present
  with_items:
    - rpcbind
    - nfs-utils

- name: Install glusterfs-server
  yum: name=glusterfs-server-{{ glusterfs_minor_version }} state=present

- name: Start & enable glusterd service
  service: name=glusterd state=started enabled=true

# belongs in a proper "storage" role, but this will have to do for now
- name: Remove irqbalance
  yum: name=irqbalance state=absent
  tags: irqbalance

# vim: set sw=2 ts=2:
