---

- block:
  - name: Install disk utilities and glusterfs-server
    yum: name={{ item }} state=present
    loop:
      - gdisk
      - xfsprogs
      - nfs-utils
      - htop
      - glusterfs-server

  - name: Start & enable glusterd service
    service: name=glusterd state=started enabled=true

  # belongs in a proper "storage" role, but this will have to do for now
  - name: Remove irqbalance
    yum: name=irqbalance state=absent
    tags: irqbalance
  tags: glusterfs-server

# vim: set sw=2 ts=2:
