---
# file: defaults/main.yml

# Web server to use. For now we don't really configure much, but use this for
# setting up some certbot pre/post scripts. Choices are currently "apache_httpd"
# and "nginx". Eventually I might start using caddy.
webserver: apache_httpd

# 1 hour timeout
nginx_ssl_session_timeout: 1h
# 10MB -> 40,000 sessions
nginx_ssl_session_cache: shared:SSL:10m
# 1400 bytes to fit in one MTU (default is 16k!)
nginx_ssl_buffer_size: 1400
nginx_ssl_dhparam: /etc/ssl/certs/dhparam.pem
nginx_ssl_protocols: 'TLSv1.2 TLSv1.3'
nginx_ssl_ecdh_curve: X25519:prime256v1:secp384r1
nginx_ssl_port: 443

# DNS resolvers for OCSP stapling (default to Cloudflare public DNS)
# See: https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling
nginx_ssl_stapling_resolver: '1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001]'

# Enable HTTP Strict Transport Security? Generally we want this everywhere, but
# since the price of undoing this is so high let's keep it off for now.
nginx_enable_hsts: false

# vim: set sw=2 ts=2:
