---
# roles/metrics/defaults/main.yml

# Unix user/group who runs victoriametrics
victoriametrics_user: victoriametrics
victoriametrics_group: victoriametrics

# The location of the main VictoriaMetrics data store
victoriametrics_data_path: /var/lib/victoriametrics/data
# The default retention period is 1 month
victoriametrics_data_retention: 3

# remoteWrite.url for vmagent on clients. We use a lookup to read the value
# from a text file instead of including it from private vars with vars_files
# because then it is not possible to override in host_vars due to the Ansible
# variable precedence rules.
#
# See: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
victoriametrics_remotewrite_url: "{{ lookup('file', 'private/vars/metrics/victoriametrics_remotewrite_url') }}"

victoriametrics_tls_crt_path: /etc/victoriametrics/victoria-metrics.crt
victoriametrics_tls_key_path: /etc/victoriametrics/victoria-metrics.key

# See: https://github.com/VictoriaMetrics/VictoriaMetrics/releases
victoriametrics_version: 1.87.7

victoriametrics_old_versions:
  - "/usr/local/bin/vmutils-linux-amd64-v1.87.6.tar.gz"

# URL for main victoriametrics tarball
victoriametrics_tarball: victoria-metrics-linux-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_tarball }}
# sha256sum from checksums.txt on GitHub releases page or manually
victoriametrics_url_checksum: b568905f1f40b1b26154cdb00e5f9491bd8174278f33d10a257682ea6cd5fa22
victoriametrics_binary_path: /usr/local/bin/victoria-metrics-prod

# URL for vmutils tarball containing vmagent, vmauth, etc.
victoriametrics_vmutils_tarball: vmutils-linux-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_vmutils_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_vmutils_tarball }}
# sha256sum from checksums.txt on release page, or manually
victoriametrics_vmutils_url_checksum: fe1760874eaa9f054028fb14a8bfaa615843b39152152fab94e5c811df5c8bfa

victoriametrics_vmauth_binary_path: /usr/local/bin/vmauth-prod
victoriametrics_vmauth_config_path: /etc/victoriametrics/vmauth.yml
# Credentials for clients connecting to vmauth (overridden in private vars)
victoriametrics_vmauth_user: "{{ lookup('file', 'private/vars/metrics/victoriametrics_vmauth_user') }}"
victoriametrics_vmauth_pass: "{{ lookup('file', 'private/vars/metrics/victoriametrics_vmauth_pass') }}"


victoriametrics_vmagent_binary_path: /usr/local/bin/vmagent-prod
# This is the path to the directory where vmagent stores its local buffer, for
# example when it can't send statistics to the main victoria-metrics host.
victoriametrics_vmagent_data_path: /var/lib/victoriametrics/vmagent-data
# The path to vmagent's prometheus.yml file
victoriametrics_vmagent_config_path: /etc/victoriametrics/prometheus.yml
# Amount of data vmagent can store if it can't reach the VictoriaMetrics server.
# The default is 0, which defeats the purpose of using vmagent entirely!
victoriametrics_vmagent_buffer: 5MB

# See: https://github.com/prometheus/node_exporter/releases
node_exporter_version: 1.6.1
node_exporter_old_versions:
  - "/usr/local/bin/node_exporter-1.6.0.linux-amd64.tar.gz"

# URL for node_exporter tarball
node_exporter_tarball: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
node_exporter_url_checksum: ecc41b3b4d53f7b9c16a370419a25a133e48c09dfc49499d63bcc0c5e0cf3d01
node_exporter_binary_path: /usr/local/bin/node_exporter

# See: https://github.com/prometheus/mysqld_exporter/releases
mysqld_exporter_version: 0.14.0
mysqld_exporter_old_versions:
  - "/usr/local/bin/mysqld_exporter-0.13.0.linux-amd64.tar.gz"

# URL for mysqld_exporter tarball
mysqld_exporter_tarball: mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz
mysqld_exporter_url: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/{{ mysqld_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
mysqld_exporter_url_checksum: c17402137a4e9745f593127f162c1003298910cb8aa7d05bee3384738de094ae
mysqld_exporter_binary_path: /usr/local/bin/mysqld_exporter
mysqld_exporter_config_path: /etc/victoriametrics/mysqld_exporter.cnf
# Override in host or group vars
mysqld_exporter_user: "{{ lookup('file', 'private/vars/metrics/mysqld_exporter_user') }}"
mysqld_exporter_pass: "{{ lookup('file', 'private/vars/metrics/mysqld_exporter_pass') }}"

# See: https://github.com/prometheus/jmx_exporter/releases
jmx_exporter_version: 0.20.0
jmx_exporter_old_versions:
  - "/etc/victoriametrics/jmx_prometheus_javaagent-0.17.0.jar"
  - "/etc/victoriametrics/jmx_prometheus_javaagent-0.19.0.jar"

# URL for jmx_exporter tarball
jmx_exporter_jar: jmx_prometheus_javaagent-{{ jmx_exporter_version }}.jar
jmx_exporter_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ jmx_exporter_version }}/{{ jmx_exporter_jar }}
# sha256sum
jmx_exporter_url_checksum: 8b67ed40485d475648c36d11d21464b484406f85faf912b3363f71a6a7861320
jmx_exporter_jar_path: /etc/victoriametrics/{{ jmx_exporter_jar }}
jmx_exporter_config_path: /etc/victoriametrics/jmx_exporter.yml

# vim: set ts=2 sw=2:
