---
# roles/metrics/defaults/main.yml

# Unix user/group who runs victoriametrics
victoriametrics_user: victoriametrics
victoriametrics_group: victoriametrics

# The location of the main VictoriaMetrics data store
victoriametrics_data_path: /var/lib/victoriametrics/data
# The default retention period is 1 month
victoriametrics_data_retention: 3

# remoteWrite.url for vmagent on clients (perhaps this should this be private,
# but if we use include_vars in the playbook then it is not possible to over-
# ride in host_vars due to precedence rules).
victoriametrics_remotewrite_url: https://41.204.190.7:8427/api/v1/write

victoriametrics_tls_crt_path: /etc/victoriametrics/victoria-metrics.crt
victoriametrics_tls_key_path: /etc/victoriametrics/victoria-metrics.key

# See: https://github.com/VictoriaMetrics/VictoriaMetrics/releases
victoriametrics_version: 1.75.0

# URL for main victoriametrics tarball
victoriametrics_tarball: victoria-metrics-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_tarball }}
# sha256sum from checksums.txt on GitHub releases page or manually
victoriametrics_url_checksum: ec08e4a014a51c9189bd7ce2a04c4c54f47b012b89e97187f3e9012a52bcd149
victoriametrics_binary_path: /usr/local/bin/victoria-metrics-prod

# URL for vmutils tarball containing vmagent, vmauth, etc.
victoriametrics_vmutils_tarball: vmutils-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_vmutils_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_vmutils_tarball }}
# sha256sum from checksums.txt on release page, or manually
victoriametrics_vmutils_url_checksum: f1e7b73d553557a3c962dc5140436651b690f57f840bafc1596b7cc2e3aa11e9

victoriametrics_vmauth_binary_path: /usr/local/bin/vmauth-prod
victoriametrics_vmauth_config_path: /etc/victoriametrics/vmauth.yml
# Credentials for clients connecting to vmauth (overridden in private vars)
victoriametrics_vmauth_user: victoriametrics
victoriametrics_vmauth_pass: password

victoriametrics_vmagent_binary_path: /usr/local/bin/vmagent-prod
# This is the path to the directory where vmagent stores its local buffer, for
# example when it can't send statistics to the main victoria-metrics host.
victoriametrics_vmagent_data_path: /var/lib/victoriametrics/vmagent-data
# The path to vmagent's prometheus.yml file
victoriametrics_vmagent_config_path: /etc/victoriametrics/prometheus.yml
# Amount of data vmagent can store if it can't reach the VictoriaMetrics server.
# The default is 0, which defeats the purpose of using vmagent entirely!
victoriametrics_vmagent_buffer: 5MB

# See: https://github.com/prometheus/node_exporter/releases
node_exporter_version: 1.3.1
# URL for node_exporter tarball
node_exporter_tarball: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
node_exporter_url_checksum: 68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949
node_exporter_binary_path: /usr/local/bin/node_exporter

# vim: set ts=2 sw=2:
