---
# roles/metrics/defaults/main.yml

# Unix user/group who runs victoriametrics
victoriametrics_user: victoriametrics
victoriametrics_group: victoriametrics

# The location of the main VictoriaMetrics data store
victoriametrics_data_path: /var/lib/victoriametrics/data
# The default retention period is 1 month
victoriametrics_data_retention: 3

# remoteWrite.url for vmagent on clients. We use a lookup to read the value
# from a text file instead of including it from private vars with vars_files
# because then it is not possible to override in host_vars due to the Ansible
# variable precedence rules.
#
# See: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
victoriametrics_remotewrite_url: "{{ lookup('file', 'private/vars/metrics/victoriametrics_remotewrite_url') }}"

victoriametrics_tls_crt_path: /etc/victoriametrics/victoria-metrics.crt
victoriametrics_tls_key_path: /etc/victoriametrics/victoria-metrics.key

# See: https://github.com/VictoriaMetrics/VictoriaMetrics/releases
victoriametrics_version: 1.93.13

victoriametrics_old_versions:
  - "/usr/local/bin/vmutils-linux-amd64-v1.87.6.tar.gz"
  - "/usr/local/bin/vmutils-linux-amd64-v1.87.7.tar.gz"
  - "/usr/local/bin/vmutils-linux-amd64-v1.87.10.tar.gz"
  - "/usr/local/bin/vmutils-linux-amd64-v1.87.14.tar.gz"

# URL for main victoriametrics tarball
victoriametrics_tarball: victoria-metrics-linux-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_tarball }}
# sha256sum from checksums.txt on GitHub releases page or manually
victoriametrics_url_checksum: 2bdfbd5a470ffe8adbbda512347550ea21f5cb2c0b8b040d1d059b05ecf2e102
victoriametrics_binary_path: /usr/local/bin/victoria-metrics-prod

# URL for vmutils tarball containing vmagent, vmauth, etc.
victoriametrics_vmutils_tarball: vmutils-linux-amd64-v{{ victoriametrics_version }}.tar.gz
victoriametrics_vmutils_url: https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/{{ victoriametrics_vmutils_tarball }}
# sha256sum from checksums.txt on release page, or manually
victoriametrics_vmutils_url_checksum: c052721f3b94fa6c42cbae3e70832c49a6b9141b7fcf29e99ec459e554e2fa1f

victoriametrics_vmauth_binary_path: /usr/local/bin/vmauth-prod
victoriametrics_vmauth_config_path: /etc/victoriametrics/vmauth.yml
# Credentials for clients connecting to vmauth (overridden in private vars)
victoriametrics_vmauth_user: "{{ lookup('file', 'private/vars/metrics/victoriametrics_vmauth_user') }}"
victoriametrics_vmauth_pass: "{{ lookup('file', 'private/vars/metrics/victoriametrics_vmauth_pass') }}"


victoriametrics_vmagent_binary_path: /usr/local/bin/vmagent-prod
# This is the path to the directory where vmagent stores its local buffer, for
# example when it can't send statistics to the main victoria-metrics host.
victoriametrics_vmagent_data_path: /var/lib/victoriametrics/vmagent-data
# The path to vmagent's prometheus.yml file
victoriametrics_vmagent_config_path: /etc/victoriametrics/prometheus.yml
# Amount of data vmagent can store if it can't reach the VictoriaMetrics server.
# The default is 0, which defeats the purpose of using vmagent entirely!
victoriametrics_vmagent_buffer: 5MB

# See: https://github.com/prometheus/node_exporter/releases
node_exporter_version: 1.7.0
node_exporter_old_versions:
  - "/usr/local/bin/node_exporter-1.6.0.linux-amd64.tar.gz"
  - "/usr/local/bin/node_exporter-1.6.1.linux-amd64.tar.gz"

# URL for node_exporter tarball
node_exporter_tarball: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
node_exporter_url_checksum: a550cd5c05f760b7934a2d0afad66d2e92e681482f5f57a917465b1fba3b02a6
node_exporter_binary_path: /usr/local/bin/node_exporter

# See: https://github.com/prometheus/mysqld_exporter/releases
mysqld_exporter_version: 0.15.0
mysqld_exporter_old_versions:
  - "/usr/local/bin/mysqld_exporter-0.13.0.linux-amd64.tar.gz"
  - "/usr/local/bin/mysqld_exporter-0.14.0.linux-amd64.tar.gz"

# URL for mysqld_exporter tarball
mysqld_exporter_tarball: mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz
mysqld_exporter_url: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/{{ mysqld_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
mysqld_exporter_url_checksum: 3973db1c46b0323a957a43916b759ee71ddab9096958ce78401fdff894b0dc51
mysqld_exporter_binary_path: /usr/local/bin/mysqld_exporter
mysqld_exporter_config_path: /etc/victoriametrics/mysqld_exporter.cnf
# Override in host or group vars
mysqld_exporter_user: "{{ lookup('file', 'private/vars/metrics/mysqld_exporter_user') }}"
mysqld_exporter_pass: "{{ lookup('file', 'private/vars/metrics/mysqld_exporter_pass') }}"


# See: https://github.com/prometheus-community/postgres_exporter/releases
postgres_exporter_version: 0.13.2
postgres_exporter_old_versions:
  - "/usr/local/bin/postgres_exporter-0.13.1.linux-amd64.tar.gz"

# URL for postgres_exporter tarball
postgres_exporter_tarball: postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz
postgres_exporter_url: https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/{{ postgres_exporter_tarball }}
# sha256sum from sha256sums.txt on GitHub releases page or manually
postgres_exporter_url_checksum: 33f820116a1c0cfc0a069d237036e05c142d216976b6fcb7c11df5abf5a537f8
postgres_exporter_binary_path: /usr/local/bin/postgres_exporter


# See: https://github.com/prometheus/jmx_exporter/releases
jmx_exporter_version: 0.20.0
jmx_exporter_old_versions:
  - "/etc/victoriametrics/jmx_prometheus_javaagent-0.17.0.jar"
  - "/etc/victoriametrics/jmx_prometheus_javaagent-0.19.0.jar"

# URL for jmx_exporter tarball
jmx_exporter_jar: jmx_prometheus_javaagent-{{ jmx_exporter_version }}.jar
jmx_exporter_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ jmx_exporter_version }}/{{ jmx_exporter_jar }}
# sha256sum
jmx_exporter_url_checksum: 8b67ed40485d475648c36d11d21464b484406f85faf912b3363f71a6a7861320
jmx_exporter_jar_path: /etc/victoriametrics/{{ jmx_exporter_jar }}
jmx_exporter_config_path: /etc/victoriametrics/jmx_exporter.yml

# vim: set ts=2 sw=2:
