---
# file: defaults/main.yml

pg_tls_cipher_suite: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"

pg_version: 9.6
pg_conf_dir: "/etc/postgresql/{{ pg_version }}/main"
pg_listen_addresses: "localhost"
pg_max_connections: 100

# vim: set sw=2 ts=2:
