---

# One-off playbook to change login credentials for provisioning user.
# Generate a SHA-512 password hash using mkpasswd or python and add
# it in ../private/vars/{{ ansible_os_family }}.yml
# using mkpasswd:
#   $ mkpasswd --method=SHA-512
# using python:
#   $ python -c 'import crypt; print(crypt.crypt("Soylent Green Is People!", "$6$saltiness"))'
#
# playbook execution:
#   $ ansible-playbook misc_plays/change_password.yml -K --limit=$host_or_group
#
# Tested on:
#   - CentOS 7
#   - CentOS 6.5
#   - Ubuntu 14.04
#   - Ubuntu 16.04
#   - Ubuntu 18.04
#   - Debian 6
#   - Debian 7
#

- hosts: all
  become: yes
  vars_files:
    - "../vars/{{ ansible_os_family }}.yml"
    - ../private/vars/common.yml
    - "../private/vars/{{ ansible_os_family }}.yml"
    - ../private/vars/ipsets.yml

  tasks:
    - name: Set password, shell, homedir for provisioning user
      when: provisioning_user is defined
      user: name={{ provisioning_user.name }} password={{ provisioning_user.password }} shell={{ provisioning_user.shell }} state={{ provisioning_user.state }} createhome=no

# vim: set sw=2 ts=2:
