---
# Single playbook to allow running the munin role on hosts which don't normally
# run the role, like those in the nomad group.
#
#   $ ansible-playbook misc_plays/munin-node.yml -l ilrinrb16 -t munin-node,firewall -K

- hosts: all
  sudo: yes
  user: provisioning
  vars_files:
    - "../vars/{{ ansible_os_family }}.yml"
    - ../private/vars/common.yml
    - "../private/vars/{{ ansible_os_family }}.yml"
    - ../private/vars/ipsets.yml
  roles:
    - common
    - munin

# vim: set sw=2 ts=2:
