---
# Update sudo for CVE-2021-3156 on all Linux servers.
# 
# See: https://www.qualys.com/2021/01/26/cve-2021-3156/baron-samedit-heap-based-overflow-sudo.txt

- hosts: all
  become: yes
  tasks:
    - name: Update sudo on Debian-based distros
      apt: name=sudo state=latest update_cache=yes
      when: ansible_os_family == "Debian"
      tags: debian

    - name: Update sudo on RedHat-based distros
      yum: name=sudo state=latest
      when: ansible_os_family == "RedHat"
      tags: redhat

# vim: set sw=2 ts=2:
