---
# Perform SLURM upgrade on HPC:
#
# 1. Upgrade SLURM on HPC head node
# 2. Restart slurmdbd, then slurmd
# 3. Upgrade SLURM on HPC compute nodes
# 4. Restart slurmd on HPC compute nodes
#
# Note: this playbook is only recommended for minor version increments. For
# major versions you should check for config changes and update manually.

- hosts: hpc
  become: true
  tasks:
    - name: Upgrade SLURM on HPC
      ansible.builtin.package:
        name: 'slurm-*'
        state: latest
        update_only: true
        update_cache: true

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart SLURM database daemon on HPC
      ansible.builtin.systemd:
        name: slurmdbd
        state: restarted

    - name: Restart slurmd on HPC
      ansible.builtin.systemd:
        name: slurmd
        state: restarted

- hosts: compute:!hpc
  become: true
  tasks:
    - name: Upgrade SLURM on compute nodes
      ansible.builtin.package:
        name: 'slurm-*'
        state: latest
        update_only: true
        update_cache: true

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart slurmd on compute nodes
      ansible.builtin.systemd:
        name: slurmd
        state: restarted

# vim: set sw=2 ts=2:
