---
# Perform Gluster 6.x -> 7.x upgrade on storage and compute nodes

- hosts: compute:storage
  become: yes
  tasks:
    - name: Clear yum cache
      command: yum clean all

    - name: Update yum cache
      command: yum makecache fast

    - name: Install Gluster 7 release channel
      yum: name=centos-release-gluster7 state=present

- hosts: storage
  become: yes
  tasks:
    - name: Stop glusterd
      systemd: name=glusterd state=stopped

    - name: Upgrade glusterfs
      yum: name=* enablerepo=centos-gluster7 disablerepo=* state=latest

    - name: Start glusterd
      systemd: name=glusterd state=started

- hosts: compute
  become: yes
  tasks:
    - name: Upgrade glusterfs
      yum: name=* enablerepo=centos-gluster7 disablerepo=* state=latest

# then reboot all storage nodes...
# then reboot all compute nodes...

# vim: set sw=2 ts=2:
