---
# Perform Gluster 9.x -> 10.x upgrade on storage and compute nodes

- hosts: compute:storage
  become: true
  tasks:
    - name: Install Gluster 10 release channel
      ansible.builtin.package:
        name: centos-release-gluster10
        state: present

- hosts: storage
  become: true
  tasks:
    - name: Stop glusterd
      ansible.builtin.systemd:
        name: glusterd
        state: stopped

    - name: Upgrade glusterfs
      ansible.builtin.package:
        name: "*"
        enablerepo: centos-gluster10
        disablerepo: "*"
        state: latest
        update_cache: true

    - name: Start glusterd
      ansible.builtin.systemd:
        name: glusterd
        state: started

- hosts: compute
  become: true
  tasks:
    - name: Upgrade glusterfs
      ansible.builtin.package:
        name: "*"
        enablerepo: centos-gluster10
        disablerepo: "*"
        state: latest
        update_cache: true

# then reboot all storage nodes...
# then reboot all compute nodes...

# vim: set sw=2 ts=2:
