---
# Perform Gluster 5.x -> 6.x upgrade on storage and compute nodes

- hosts: compute:storage
  become: yes
  tasks:
    - name: Clear yum cache
      command: yum clean all

    - name: Update yum cache
      command: yum makecache fast

    - name: Install Gluster 6 release channel
      yum: name=centos-release-gluster6 state=present

- hosts: storage
  become: yes
  tasks:
    - name: Stop glusterd
      systemd: name=glusterd state=stopped
      yum: name=centos-release-gluster6 state=present

    - name: Upgrade glusterfs
      yum: name=* enablerepo=centos-gluster6 disablerepo=* state=latest

    - name: Start glusterd
      systemd: name=glusterd state=started

- hosts: compute
  become: yes
  tasks:
    - name: Install Gluster 6 release channel
      yum: name=centos-release-gluster6 state=present

    - name: Upgrade glusterfs
      yum: name=* enablerepo=centos-gluster6 disablerepo=* state=latest

# then reboot all storage nodes...
# then reboot all compute nodes...

# vim: set sw=2 ts=2:
