---
# Perform SLURM upgrade on HPC:
#
# 1. Upgrade SLURM on HPC head node
# 2. Restart slurmdbd, then slurmd
# 3. Upgrade SLURM on HPC compute nodes
# 4. Restart slurmd on HPC compute nodes
#
# Note: this playbook is only recommended for minor version increments. For
# major versions you should check for config changes and update manually.

- hosts: hpc
  become: true
  tasks:
  # Note: We name the packages explicitly so we can use `state: latest` with
  # `update_only: true`. If we try to update "slurm-*" yum/dnf will see the
  # other available slurm packages in the repository that we don't have in-
  # stalled, and will refuse to run because those are not updates.
  #
  # See: https://github.com/ansible/ansible/issues/77770
    - name: Upgrade SLURM on HPC
      ansible.builtin.package:
        name:
          - slurm
          - slurm-contribs
          - slurm-devel
          - slurm-example-configs
          - slurm-pam_slurm
          - slurm-slurmctld
          - slurm-slurmd
          - slurm-slurmdbd
        state: latest
        update_only: true
        update_cache: true
      register: upgrade_slurm_packages

    - name: Reload systemd
      ansible.builtin.systemd_service: # noqa no-handler
        daemon_reload: true
      when: upgrade_slurm_packages is changed

    # this ensures we get the latest config file changes and restart daemons in
    # the correct order.
    - name: Include slurm tasks from compute role
      ansible.builtin.include_role:
        name: compute
        tasks_from: slurm

- hosts: compute:!hpc
  become: true
  tasks:
    - name: Upgrade SLURM on compute nodes
      ansible.builtin.package:
        name:
          - slurm
          - slurm-contribs
          - slurm-devel
          - slurm-example-configs
          - slurm-pam_slurm
          - slurm-slurmd
        state: latest
        update_only: true
        update_cache: true
      register: upgrade_slurm_packages

    - name: Reload systemd
      ansible.builtin.systemd_service: # noqa no-handler
        daemon_reload: true
      when: upgrade_slurm_packages is changed

    - name: Include slurm tasks from compute role
      ansible.builtin.include_role:
        name: compute
        tasks_from: slurm

# vim: set sw=2 ts=2:
