---

- name: Configure munin scraper
  ansible.builtin.import_tasks: munin.yml
  tags: munin

- name: Configure munin listener
  ansible.builtin.import_tasks: munin-node.yml
  tags: munin-node

# vim: set sw=2 ts=2:
