---
- name: Uninstall munin-node
  ansible.builtin.package:
    name: munin-node
    state: absent
  tags: packages

# Enable sensors support if this is a bare metal machine. The way we check this
# is to consult ansible_virtualization_role, which always returns "host" if the
# host is bare metal.
- name: Install sensor packages (Red Hat)
  ansible.builtin.package:
    name:
      - lm_sensors # for CPU package and PCI card temperatures
      - hddtemp    # for hard drive temperatures
    state: present
  when:
    - ansible_virtualization_role == "host"
    - ansible_os_family == "RedHat"
  tags: packages

- name: Install sensor packages (Debian)
  ansible.builtin.package:
    name:
      - lm-sensors
    state: present
  when:
    - ansible_virtualization_role == "host"
    - ansible_os_family == "Debian"
  tags: packages

- name: Disable Munin temperature and fan plugins
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/munin/plugins/sensors_fan
    - /etc/munin/plugins/sensors_temp
  when: ansible_virtualization_role == "host"

# some nice things to have for munin-node on Ubuntu (12.04 and 14.04 right now)
# libwww-perl for munin's nginx_status check
- name: Uninstall munin-node deps
  ansible.builtin.package:
    name: libwww-perl
    state: absent
  when: ansible_distribution == "Ubuntu"
  tags: packages

# Some nice things to have on Ubuntu Tomcat servers:
#   - ruby for munin's tomcat checks
#   - libxml-simple-perl for munin's tomcat checks
#   - libdbd-pg-perl for munin's postgres check
#   - munin-plugins-java to monitor Tomcat via JMX
- name: Uninstall munin-node Tomcat deps
  when: (ansible_distribution == "Ubuntu" and ("dspace" in group_names or "solr" in group_names or "postgres" in group_names))
  ansible.builtin.package:
    name: ['ruby', 'libxml-simple-perl', 'libdbd-pg-perl', 'munin-plugins-java']
    state: absent
  tags: packages

- name: Remove munin Tomcat plugin
  when: (ansible_distribution == "Ubuntu" and ("dspace" in group_names or "solr" in group_names))
  ansible.builtin.file:
    path: /etc/munin/plugin-conf.d/tomcat
    state: absent

- name: Configure munin DSpace Sessions plugin
  ansible.builtin.file:
    path: /etc/munin/plugins/jmx_dspace_sessions
    state: absent
  when:
    - ansible_distribution == "Ubuntu"
    - '"dspace" in group_names'

- name: Enable munin JMX dbpools plugin
  ansible.builtin.file:
    path: /etc/munin/plugins/jmx_tomcat_dbpools
    state: absent
  when:
    - ansible_distribution == "Ubuntu"
    - '"dspace" in group_names'

- name: Remove munin-node.conf
  ansible.builtin.file:
    path: /etc/munin/munin-node.conf
    state: absent

# vim: set sw=2 ts=2:
