---
- name: Uninstall munin
  ansible.builtin.package:
    name: munin
    state: absent
  tags: packages

- name: Remove munin configuration file
  ansible.builtin.file:
    path: /etc/munin/munin.conf
    state: absent

# vim: set sw=2 ts=2:
