---
# file: roles/postgres/tasks/ubuntu.yml

- name: Remove PGDG key from apt-key
  ansible.builtin.apt_key:
    id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    state: absent
  tags:
    - packages
    - postgresql

- name: Check PGDG package signing key
  ansible.builtin.stat:
    path: /usr/share/keyrings/ACCC4CF8.asc
  register: pgdg_signing_key_stat
  tags:
    - packages
    - postgresql

- name: Download PGDG package signing key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/keyrings/ACCC4CF8.asc
    owner: root
    group: root
    mode: "0644"
  register: download_pgdg_signing_key
  when: not pgdg_signing_key_stat.stat.exists
  tags:
    - packages
    - postgresql

- name: Add PGDG repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/ACCC4CF8.asc] https://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    filename: pgdg
    state: present
  register: add_pgdg_apt_repository
  tags:
    - packages
    - postgresql

- name: Update apt cache
  ansible.builtin.apt: # noqa no-handler
    update_cache: true
  when:
    (download_pgdg_signing_key.status_code is defined and download_pgdg_signing_key.status_code == 200) or
    add_pgdg_apt_repository is changed
  tags:
    - packages
    - postgresql

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name:
      - postgresql-{{ pg_version }}
      - postgresql-client-{{ pg_version }}
    cache_valid_time: 3600
    state: present
  notify:
    - restart postgresql
  tags:
    - packages
    - postgresql

- name: Create additional PostgreSQL config directory
  ansible.builtin.file:
    path: "{{ pg_conf_dir }}/conf.d"
    mode: "0755"
    owner: postgres
    group: postgres
    state: directory
  tags: postgresql

- name: Set custom PostgreSQL variables
  ansible.builtin.template:
    src: pg_confd_vars.conf.j2
    dest: "{{ pg_conf_dir }}/conf.d/custom_vars.conf"
    mode: "0644"
    owner: postgres
    group: postgres
  when: pg_confd_vars is defined
  notify:
    - restart postgresql
  tags: postgresql

- name: Copy PostgreSQL configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { src: "postgresql-{{ pg_version }}.conf.j2", dest: "{{ pg_conf_dir }}/postgresql.conf", mode: "0644", owner: postgres, group: postgres }
    - { src: "pg_hba-{{ pg_version }}.conf.j2", dest: "{{ pg_conf_dir }}/pg_hba.conf", mode: "0640", owner: postgres, group: postgres }
  notify:
    - restart postgresql
  tags: postgresql

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  tags: postgresql

# vim: set sw=2 ts=2:
