---
# file: tasks/ubuntu.yml

- name: Install postgresql
  apt: name={{ item }} update_cache=yes state=present cache_valid_time=86400
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
  notify:
    - restart postgres

- name: Copy postgres configs
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: 'postgresql-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/postgresql.conf', mode: '0644', owner: 'postgres', group: 'postgres' }
    - { src: 'pg_hba-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/pg_hba.conf', mode: '0640', owner: 'postgres', group: 'postgres' }
  notify: restart postgres

- name: start & enable postgres
  service: name=postgresql state=started enabled=true

# vim: set sw=2 ts=2:
