---
# file: tasks/ubuntu.yml

- block:
  - name: Add PGDG apt list file
    template: src=pgdg.list.j2 dest=/etc/apt/sources.list.d/pgdg.list owner=root group=root mode=0644
    tags: packages

  - name: Import PGDG repo keys
    apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc" state=present
    tags: packages

  - name: Install postgresql
    apt: name={{ item }} update_cache=yes state=present cache_valid_time=3600
    loop:
      - postgresql-{{ pg_version }}
      - postgresql-client-{{ pg_version }}
      - postgresql-contrib-{{ pg_version }}
    notify:
      - restart postgres
    tags: packages

  - name: Create additional postgresql configs. directory
    file: path={{ pg_conf_dir }}/conf.d mode=0755 owner=postgres group=postgres state=directory

  - name: Set custom postgresql variables
    template: src=pg_confd_vars.conf.j2 dest={{ pg_conf_dir }}/conf.d/custom_vars.conf mode=0644 owner=postgres group=postgres
    when: pg_confd_vars is defined
    notify: restart postgres

  - name: Copy postgres configs
    template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
    loop:
      - { src: 'postgresql-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/postgresql.conf', mode: '0644', owner: 'postgres', group: 'postgres' }
      - { src: 'pg_hba-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/pg_hba.conf', mode: '0640', owner: 'postgres', group: 'postgres' }
    notify: restart postgres

  - name: start & enable postgres
    service: name=postgresql state=started enabled=true
  tags: postgresql
# vim: set sw=2 ts=2:
