---
# file: roles/postgres/tasks/ubuntu.yml

- name: Add PGDG apt list file
  ansible.builtin.template:
    src: pgdg.list.j2
    dest: /etc/apt/sources.list.d/pgdg.list
    owner: root
    group: root
    mode: 0644
  register: add_postgresql_apt_repository
  tags:
    - packages
    - postgresql

- name: Import PGDG repo keys
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  register: add_postgresql_apt_key
  tags:
    - packages
    - postgresql

# Update cache if apt source file changed. ansible-lint doesn't like when we
# use "is changed" but that's all we can do here. At least for the apt_key
# status we can check whether "after" is defined, as that is only true when
# the key was added.
- name: Update apt cache
  ansible.builtin.apt: # noqa no-handler
    update_cache: true
  when:
    add_postgresql_apt_key.after is defined
    add_postgresql_apt_repository is changed
  tags:
    - packages
    - postgresql

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name:
      - postgresql-{{ pg_version }}
      - postgresql-client-{{ pg_version }}
      - postgresql-contrib-{{ pg_version }}
    cache_valid_time: 3600
    state: present
  notify:
    - restart postgresql
  tags:
    - packages
    - postgresql

- name: Create additional PostgreSQL config directory
  ansible.builtin.file:
    path: "{{ pg_conf_dir }}/conf.d"
    mode: 0755
    owner: postgres
    group: postgres
    state: directory
  tags: postgresql

- name: Set custom PostgreSQL variables
  ansible.builtin.template:
    src: pg_confd_vars.conf.j2
    dest: "{{ pg_conf_dir }}/conf.d/custom_vars.conf"
    mode: 0644
    owner: postgres
    group: postgres
  when: pg_confd_vars is defined
  notify:
    - restart postgresql
  tags: postgresql

- name: Copy PostgreSQL configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { src: 'postgresql-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/postgresql.conf', mode: '0644', owner: 'postgres', group: 'postgres' }
    - { src: 'pg_hba-{{ pg_version }}.conf.j2', dest: '{{ pg_conf_dir }}/pg_hba.conf', mode: '0640', owner: 'postgres', group: 'postgres' }
  notify:
    - restart postgresql
  tags: postgresql

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  tags: postgresql

# vim: set sw=2 ts=2:
