---
# file: roles/metrics/tasks/client.yml
#
# Setup for clients. Configures exporters and vmagent. All hosts should run the
# node_exporter and vmagent. Others may run mysqld_exporter, etc. We configure
# the exporters before vmagent so that it can start scraping them immediately
# after it starts up.

- name: Configure node_exporter
  import_tasks: node_exporter.yml

- name: Configure mysqld_exporter
  include_tasks: mysqld_exporter.yml
  when:
    - extra_victoriametrics_exporters is defined
    - '"mysqld" in extra_victoriametrics_exporters'

# Currently only run on DSpace hosts, with some dependent stuff configured in
# the dspace role.
- name: Configure jmx_exporter
  include_tasks: jmx_exporter.yml
  when: '"dspace" in group_names'

- name: Configure vmutils
  import_tasks: vmutils.yml

# vim: set sw=2 ts=2:
