---
# file: roles/metrics/tasks/common.yml
#
# Common setup for VictoriaMetrics servers and clients.

- name: Add VictoriaMetrics group
  ansible.builtin.group:
    name: "{{ victoriametrics_group }}"
    system: true

- name: Add VictoriaMetrics user
  ansible.builtin.user:
    name: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    system: true
    create_home: false

- name: Create /etc/victoriametrics directory
  ansible.builtin.file:
    path: /etc/victoriametrics
    state: directory
    owner: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    mode: 0755

- name: Copy TLS certificate
  ansible.builtin.copy:
    src: etc/victoriametrics/victoria-metrics.crt
    dest: "{{ victoriametrics_tls_crt_path }}"
    owner: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    mode: 0644

- name: Read TLS key
  ansible.builtin.set_fact:
    tls_key_content: "{{ lookup('file', 'private/data/metrics/victoria-metrics.key') }}"
  when:
    - victoriametrics_role is defined
    - victoriametrics_role == 'server'

- name: Copy TLS key
  ansible.builtin.copy:
    content: "{{ tls_key_content }}"
    dest: "{{ victoriametrics_tls_key_path }}"
    owner: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    mode: 0600
  when: tls_key_content is defined

# vim: set sw=2 ts=2:
