---
# file: roles/metrics/tasks/node_exporter.yml
#
# Download the vmutils tarball to /usr/local/bin. The binary in the tarball does
# not have a version in its name and I don't want to parse CLI output, so all we
# we can do is check if the tarball for the current version exists.
#

- name: Check node_exporter version
  ansible.builtin.stat:
    path: "/usr/local/bin/{{ node_exporter_tarball }}"
  register: node_exporter_stat

- name: Download node_exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_url }}"
    dest: "/usr/local/bin/{{ node_exporter_tarball }}"
    checksum: "sha256:{{ node_exporter_url_checksum }}"
  register: node_exporter_download
  when: not node_exporter_stat.stat.exists

- name: Unzip node_exporter
  ansible.builtin.unarchive:
    src: "/usr/local/bin/{{ node_exporter_tarball }}"
    remote_src: yes
    dest: /usr/local/bin
    extra_opts:
      - --strip-components
      - 1
      - node_exporter-1.3.1.linux-amd64/node_exporter
  when: node_exporter_download is changed

- name: Remove old node_exporter tarballs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/bin/node_exporter-1.3.0.linux-amd64.tar.gz"

- name: Configure node-exporter systemd service
  ansible.builtin.template:
    src: etc/systemd/system/node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node-exporter

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start and enable node-exporter
  ansible.builtin.systemd:
    name: node-exporter.service
    state: started
    enabled: yes

# vim: set sw=2 ts=2:
