---
# file: roles/metrics/tasks/server.yml

- name: Check VictoriaMetrics version
  ansible.builtin.stat:
    path: /usr/local/bin/{{ victoriametrics_tarball }}
  register: victoriametrics_stat

- name: Download VictoriaMetrics
  ansible.builtin.get_url:
    url: "{{ victoriametrics_url }}"
    dest: /usr/local/bin/{{ victoriametrics_tarball }}
    checksum: sha256:{{ victoriametrics_url_checksum }}
    mode: "0640"
  register: victoriametrics_download
  when: not victoriametrics_stat.stat.exists

- name: Unzip VictoriaMetrics
  ansible.builtin.unarchive:
    src: /usr/local/bin/{{ victoriametrics_tarball }}
    remote_src: true
    dest: /usr/local/bin
  when:
    - victoriametrics_download.status_code is defined
    - victoriametrics_download.status_code == 200
  notify:
    - restart victoria-metrics
    - restart vmauth

- name: Remove old VictoriaMetrics tarballs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ victoriametrics_old_versions }}"

- name: Configure vmauth.yml
  ansible.builtin.template:
    src: etc/victoriametrics/vmauth.yml.j2
    dest: "{{ victoriametrics_vmauth_config_path }}"
    owner: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    mode: "0600"
  notify:
    - restart vmauth

- name: Create VictoriaMetrics data directory
  ansible.builtin.file:
    path: "{{ victoriametrics_data_path }}"
    state: directory
    owner: "{{ victoriametrics_user }}"
    group: "{{ victoriametrics_group }}"
    mode: "0770"

- name: Copy VictoriaMetrics server service unit
  ansible.builtin.template:
    src: etc/systemd/system/victoria-metrics.service.j2
    dest: /etc/systemd/system/victoria-metrics.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart victoria-metrics

- name: Copy VictoriaMetrics vmauth service unit
  ansible.builtin.template:
    src: etc/systemd/system/victoria-metrics-vmauth.service.j2
    dest: /etc/systemd/system/victoria-metrics-vmauth.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart vmauth

# vim: set sw=2 ts=2:
